// CMS-managed content. The admin panel writes src/data/catalog.json; this
// module reads the latest file on every render so edits take effect
// immediately. (Originally generated by scripts/crawl-catalog.mjs.)

import { loadLocalizedData } from "@/lib/data-files";
import { DEFAULT_LOCALE, type Locale } from "@/i18n/config";

export interface CatalogLabel {
  text: string;
  backgroundColor?: string;
  textColor?: string;
}

export interface CatalogProduct {
  id: string;
  slug: string;
  name: string;
  productType?: string;
  designText?: string;
  price: number | null;
  originalPrice?: number | null;
  image: string | null;
  labels: CatalogLabel[];
  detail: {
    images: (string | null)[];
    benefits: string[];
    dimension?: string | null;
    materials: string[];
    care: string[];
    description?: string | null;
    intendedFor?: string | null;
    packageCount?: string | null;
    usage?: string | null;
    resultReading?: string | null;
    precautions?: string | null;
    storage?: string | null;
  } | null;
}

export interface CatalogCategory {
  id: string;
  name: string;
  slug: string;
  url: string;
  image: string | null;
  subs: { name: string; slug: string; url: string; image: string | null }[];
  products: CatalogProduct[];
}

export interface CatalogData {
  catalogCategories: CatalogCategory[];
  channelCategories: CatalogCategory[];
}

export function catalogData(locale: Locale = DEFAULT_LOCALE): CatalogData {
  return loadLocalizedData<CatalogData>("catalog.json", locale);
}
