// CMS-managed content. The admin panel writes src/data/menu-panels.json; this
// module reads the latest file on every render. (Originally generated by
// scripts/extract-menu.mjs.)

import { loadLocalizedData } from "@/lib/data-files";
import { DEFAULT_LOCALE, type Locale } from "@/i18n/config";

export interface MenuImageCard {
  title: string;
  href: string;
  image: string | null;
  description?: string | null;
}

export interface MenuColumn {
  heading: string | null;
  intro: string | null;
  cards: MenuImageCard[];
  thumbnails: MenuImageCard[];
  links: { title: string; href: string }[];
}

export interface MenuPanel {
  label: string;
  href: string;
  columns: MenuColumn[];
}

interface MenuPanelsData {
  menuPanels: MenuPanel[];
  appPromotion: {
    desc: string;
    qrCodeUrl: string;
    appDownloadUrl: string;
  };
}

export function getMenuPanels(locale: Locale = DEFAULT_LOCALE): MenuPanel[] {
  return loadLocalizedData<MenuPanelsData>("menu-panels.json", locale).menuPanels;
}

export function getAppPromotion(locale: Locale = DEFAULT_LOCALE): MenuPanelsData["appPromotion"] {
  return loadLocalizedData<MenuPanelsData>("menu-panels.json", locale).appPromotion;
}
