// Extracts the full header mega-menu data from a live ikea.cn page payload and
// writes src/data/menu-panels.ts. Handles image-text-cards, pub-image banners,
// link-lists (plain + thumbnails), and text headings.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, "..");
const SITE = "https://www.ikea.cn";
const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36";

function parseNuxtPayload(payload) {
  const val = (i) => {
    if (typeof i === "number" && Number.isInteger(i) && i >= 0 && i < payload.length) {
      const item = payload[i];
      if (Array.isArray(item) && item.length >= 2 && typeof item[0] === "string") {
        const t = item[0];
        if (["string","number","boolean","null","undefined","Date","BigInt"].includes(t)) {
          return item.length > 1 ? item[1] : undefined;
        }
        if (t === "object") { const out = {}; for (const [k, ref] of item[1]) out[val(k)] = val(ref); return out; }
        if (t === "Set") return item[1].map((x) => val(x));
        return item.slice(1).map((x) => val(x));
      }
      if (Array.isArray(item)) return item.map((x) => val(x));
      if (item !== null && typeof item === "object") {
        const out = {};
        for (const k of Object.keys(item)) out[k] = val(item[k]);
        return out;
      }
      return item;
    }
    return i;
  };
  return val(payload[0][1]);
}

async function getLayout() {
  const res = await fetch(SITE + "/cn/zh/rooms/living-room/", {
    headers: { "User-Agent": UA },
  });
  const html = await res.text();
  const m = html.match(
    /<script type="application\/json" data-nuxt-data="nuxt-app" data-ssr="true" id="__NUXT_DATA__">(.*?)<\/script>/s,
  );
  const root = parseNuxtPayload(JSON.parse(m[1]));
  const data = root.data[0];
  return data[Object.keys(data)[0]].layout;
}

function normalizeHref(href) {
  if (!href) return null;
  if (href.startsWith("/")) return href;
  const m = href.match(/^https?:\/\/www\.ikea\.cn(\/[^?#]*)/);
  return m ? m[1] : href;
}

function stripHtml(text) {
  return (text ?? "").replace(/<[^>]+>/g, "").replace(/\s+/g, " ").trim();
}

function extractColumn(content) {
  const column = { heading: null, intro: null, cards: [], thumbnails: [], links: [] };
  for (const node of content ?? []) {
    const type = node?.type;
    if (type === "text" || type === "pub-text") {
      const text = stripHtml(node.text ?? node.content);
      if (/^<h2/i.test(node.text ?? "") || /^h2/.test(type)) {
        if (!column.heading) column.heading = text;
      } else if (!column.intro) {
        column.intro = text;
      }
      continue;
    }
    if (type === "image-text-card") {
      const href = normalizeHref(node.link?.url);
      if (href) {
        column.cards.push({
          title: node.title ?? "",
          href,
          image: node.image?.url ?? null,
        });
      }
      continue;
    }
    if (type === "pub-image") {
      const href = normalizeHref(node.link?.url);
      if (href) {
        column.cards.push({
          title: node.alt ?? node.caption ?? "",
          href,
          image: node.image?.url ?? null,
        });
      }
      continue;
    }
    if (type === "link-list") {
      const elems = node.model?.links?.elements ?? [];
      const thumb = node.model?.layout === "thumbnails";
      for (const el of elems) {
        const href = normalizeHref(el.link);
        if (!href) continue;
        const item = {
          title: el.title ?? "",
          href,
          image: el.image?.url ?? null,
          description: el.description ?? null,
        };
        if (thumb) column.thumbnails.push(item);
        else column.links.push({ title: item.title, href: item.href });
      }
      continue;
    }
  }
  return column;
}

const layout = await getLayout();
const header = layout.menus.header ?? [];

const panels = header.map((item) => {
  const columns = [];
  const setArr = Array.isArray(item.set) ? item.set : [];
  const href = normalizeHref(setArr[0]?.link) ?? "/";
  for (const comp of item.components ?? []) {
    const model = comp.model ?? {};
    const content = model.content ?? model;
    const elems = Array.isArray(content?.elements) ? content.elements : [content];
    for (const col of elems) {
      const column = extractColumn(col.content ?? []);
      if (column.cards.length || column.thumbnails.length || column.links.length) {
        columns.push(column);
      }
    }
  }
  return { label: item.title ?? "", href, columns };
});

const appPromotion = layout.menus.appPromotion ?? {};
const output = `// Generated by scripts/extract-menu.mjs — do not hand-edit.
export interface MenuImageCard {
  title: string;
  href: string;
  image: string | null;
  description?: string | null;
}

export interface MenuColumn {
  heading: string | null;
  intro: string | null;
  cards: MenuImageCard[];
  thumbnails: MenuImageCard[];
  links: { title: string; href: string }[];
}

export interface MenuPanel {
  label: string;
  href: string;
  columns: MenuColumn[];
}

export const menuPanels: MenuPanel[] = ${JSON.stringify(panels, null, 2)};

export const appPromotion = ${JSON.stringify(
    {
      desc: appPromotion.desc ?? "",
      qrCodeUrl: appPromotion.qrCodeUrl ?? null,
      appDownloadUrl: appPromotion.appDownloadUrl ?? null,
    },
    null,
    2,
  )};
`;
fs.writeFileSync(path.join(repoRoot, "src", "data", "menu-panels.ts"), output);
console.log("panels:", panels.length);
for (const p of panels) {
  const cards = p.columns.reduce((s, c) => s + c.cards.length, 0);
  const thumbs = p.columns.reduce((s, c) => s + c.thumbnails.length, 0);
  const links = p.columns.reduce((s, c) => s + c.links.length, 0);
  console.log(` ${p.label}: ${p.columns.length} columns | cards=${cards} thumbs=${thumbs} links=${links}`);
}
