// CMS-managed content. The admin panel writes src/data/menu-panels.json; this
// module reads the latest file on every render. (Originally generated by
// scripts/extract-menu.mjs.)

import { loadDataJson } from "@/lib/data-files";

export interface MenuImageCard {
  title: string;
  href: string;
  image: string | null;
  description?: string | null;
}

export interface MenuColumn {
  heading: string | null;
  intro: string | null;
  cards: MenuImageCard[];
  thumbnails: MenuImageCard[];
  links: { title: string; href: string }[];
}

export interface MenuPanel {
  label: string;
  href: string;
  columns: MenuColumn[];
}

interface MenuPanelsData {
  menuPanels: MenuPanel[];
  appPromotion: {
    desc: string;
    qrCodeUrl: string;
    appDownloadUrl: string;
  };
}

export function getMenuPanels(): MenuPanel[] {
  return loadDataJson<MenuPanelsData>("menu-panels.json").menuPanels;
}

export function getAppPromotion(): MenuPanelsData["appPromotion"] {
  return loadDataJson<MenuPanelsData>("menu-panels.json").appPromotion;
}
