// Generated by scripts/crawl-pages.mjs — do not hand-edit.
export interface ContentSection {
  heading: string;
  text: string;
  image: string | null;
}

export interface ContentPageData {
  url: string;
  family: string;
  title: string;
  h1: string;
  hero: string | null;
  sections: ContentSection[];
  links: string[];
}

export const contentPages: ContentPageData[] = [
 {
  "url": "/cn/zh/rooms/bedroom/",
  "family": "rooms",
  "title": "卧室",
  "h1": "卧室",
  "hero": null,
  "sections": [
   {
    "heading": "夏日好眠，从选择床品开始",
    "text": "",
    "image": null
   },
   {
    "heading": "陪你度过炎炎夏日",
    "text": "试试凉感寝具带来的凉爽睡眠体验，畅享清凉好梦眠 ❄",
    "image": null
   },
   {
    "heading": "找到你的个性风格",
    "text": "选择你心仪的色彩、图案和材质，搭配出理想中的个性卧室！",
    "image": null
   },
   {
    "heading": "成套选购卧室家具",
    "text": "卧室家具组合可以帮助你快速地打造配套完整的谐美卧室。各种必需品一应俱全，包括睡床、便利的床头桌和衣物储物装置。我们的全套卧室家具组合可以让你像点比萨饼一样轻松地布置心仪卧室！",
    "image": null
   },
   {
    "heading": "更多卧室家具系列",
    "text": "",
    "image": null
   },
   {
    "heading": "PAX 帕克思卧室储物系列",
    "text": "一个井然有序的家会让人神清气爽、身心放松。选择PAX 帕克思衣柜和KOMPLEMENT 康普蒙 系列内部收纳件，可以自由决定尺寸、颜色和样式等，为你提供适合不同大小空间的衣物解决方案，在细节处充分彰显个性。",
    "image": null
   },
   {
    "heading": "测试过的 安心材质",
    "text": "甲醛释放量严格把关，安心之选。",
    "image": null
   },
   {
    "heading": "打造理想卧室的指南",
    "text": "",
    "image": null
   },
   {
    "heading": "浏览所有卧室布置灵感",
    "text": "",
    "image": null
   },
   {
    "heading": "了解如何整理卧室家纺和衣物",
    "text": "",
    "image": null
   }
  ],
  "links": [
   "/",
   "/cn/zh/cat/54992",
   "/cn/zh/cat/bm003",
   "/cn/zh/cat/bm002",
   "/cn/zh/cat/20656",
   "/cn/zh/cat/19053",
   "/cn/zh/cat/st004",
   "/cn/zh/cat/10550",
   "/cn/zh/cat/tl004",
   "/cn/zh/cat/li002",
   "/cn/zh/cat/10653",
   "/cn/zh/rooms/home-decoration-pub8982d9ca",
   "/cn/zh/new/seasonal-textile-pub2fe7fbf2",
   "/cn/zh/inspiration/detail/01C50174-C83C-44FC-95B2EBF81B9A31FE"
  ]
 },
 {
  "url": "/cn/zh/rooms/living-room/",
  "family": "rooms",
  "title": "灵活的客厅搭配，满足每个人的个性需求",
  "h1": "客厅",
  "hero": null,
  "sections": [
   {
    "heading": "展示与收纳之间找到平衡",
    "text": "",
    "image": null
   },
   {
    "heading": "舒适地坐着休息，或躺着睡觉",
    "text": "",
    "image": null
   },
   {
    "heading": "个性单品布置客厅休闲区",
    "text": "造型感单椅、层叠式小推车...IKEA PS 2026 系列用更有辨识度的线条和轮廓，为客厅增添更多趣味。",
    "image": null
   },
   {
    "heading": "更低价格的客厅好物推荐",
    "text": "通过大批量生产和智能设计，IKEA把高品质变得更实惠。现在，用更少的预算，为你的客厅增添更多缤纷的生活细节。",
    "image": null
   },
   {
    "heading": "换上温暖的日常",
    "text": "",
    "image": null
   },
   {
    "heading": "客厅布置指南和案例",
    "text": "储物方式会随着家庭生活的变化不断调整。当不再需要把一切收得严严实实，是时候让喜爱的装饰品回归视野，让收纳与展示同时实现。 你可以轻松地将客厅变为卧室或客房，睡个好觉后再将其恢复原样。 造型感单椅、层叠式小推车...IKEA PS 2026 系列用更有辨识度的线条和轮廓，为客厅增添更多趣味。",
    "image": null
   },
   {
    "heading": "查看所有客厅布置建议",
    "text": "",
    "image": null
   },
   {
    "heading": "万事俱备的储物墙壁",
    "text": "",
    "image": null
   },
   {
    "heading": "巧用墙面，制造更多空间",
    "text": "",
    "image": null
   },
   {
    "heading": "有了沙发床，任何房间都可以是客房",
    "text": "",
    "image": null
   }
  ],
  "links": [
   "/",
   "/cn/zh/cat/fu003",
   "/cn/zh/cat/10663",
   "/cn/zh/cat/fu006",
   "/cn/zh/cat/10705",
   "/cn/zh/cat/10475",
   "/cn/zh/cat/st002",
   "/cn/zh/cat/st003",
   "/cn/zh/cat/li002",
   "/cn/zh/cat/10653",
   "/cn/zh/cat/tl001",
   "/cn/zh/cat/st001",
   "/cn/zh/cat/de001",
   "/cn/zh/cat/700411"
  ]
 },
 {
  "url": "/cn/zh/rooms/kitchen/",
  "family": "rooms",
  "title": "宜家厨房家具-厨房整体用品家具-一体厨柜厨具",
  "h1": "厨房",
  "hero": "/images/pages/cn-zh-rooms-kitchen/img-1.png",
  "sections": [
   {
    "heading": "简单4步，打造你的梦想厨房",
    "text": "从款式、饰面到材质，您都可以自由发现和搭配，逐步塑造心中的理想厨房。让每一个想法都被看见，让每一处细节都更贴合您的生活方式，打造一个真正属于您的、像您的故事一样独特的宜家厨房。",
    "image": null
   },
   {
    "heading": "第一步 找到你的风格",
    "text": "选择您喜欢的风格，从传统到乡村风再到现代厨房的风格，以及您对颜色、材料和功能的偏好。",
    "image": null
   },
   {
    "heading": "第二步 测量你的空间",
    "text": "",
    "image": null
   },
   {
    "heading": "厨房3天焕新",
    "text": "最快3天，一站式服务。",
    "image": null
   },
   {
    "heading": "第三步 设计和计划",
    "text": "花点时间想象一下您理想的厨房会是什么样子。您可以开始尝试使用我们的在线工具进行组合，或者如果您愿意，可以与我们的专家进行免费预约。设计您梦想中的厨房比看起来更容易！",
    "image": null
   },
   {
    "heading": "一对一服务",
    "text": "价格透明，省心又放心。",
    "image": null
   },
   {
    "heading": "获取厨房报价",
    "text": "轻松几步，自选厨房组合",
    "image": null
   },
   {
    "heading": "分期付款6期0息",
    "text": "",
    "image": null
   },
   {
    "heading": "25年免费质保",
    "text": "",
    "image": null
   },
   {
    "heading": "环保现货",
    "text": "",
    "image": null
   },
   {
    "heading": "价格透明，无隐藏增项",
    "text": "",
    "image": null
   }
  ],
  "links": [
   "/",
   "/cn/zh/cat/ka003",
   "/cn/zh/cat/24264",
   "/cn/zh/cat/24255",
   "/cn/zh/cat/10471",
   "/cn/zh/cat/ka002",
   "/cn/zh/cat/10482",
   "/cn/zh/cat/24263",
   "/cn/zh/cat/15937",
   "/cn/zh/cat/kt003",
   "/cn/zh/h5page/?url=https://store-companion.ikea.cn/design-leads/kitchen.html?channel=kitchen_IRW M2&cl_sr=IRW M2&source=NEW_WEB",
   "/cn/zh/h5page/?url=https://kitchen.web.ikea.cn/kitchen-offline",
   "/cn/zh/landing-page/cn--zh--56b12ffbb39e4a84a226bb179c08eb37?productIds=&topProductFullIds=&assemblyProductFullIds=&utm_source=&utm_medium=&utm_campaign=&utm_content=&utm_term=&web_new=",
   "/cn/zh/landing-page/cn--zh--f2540d3bb00111e7b23503ef832e0d7f?productIds=&topProductFullIds=&assemblyProductFullIds=&utm_source=&utm_medium=&utm_campaign=&utm_content=&utm_term=&web_new="
  ]
 },
 {
  "url": "/cn/zh/rooms/dining/",
  "family": "rooms",
  "title": "适合每个空间和风格的餐厅家具_IKEA宜家家居官网",
  "h1": "餐厅",
  "hero": "/images/pages/cn-zh-rooms-dining/img-1.png",
  "sections": [
   {
    "heading": "感受全新设计的餐桌的美",
    "text": "",
    "image": null
   },
   {
    "heading": "更低价格的餐厅好物推荐",
    "text": "通过大批量生产和智能设计，把高品质变得更实惠。现在，用更少的预算，为你的餐厅增添更多缤纷的生活细节。",
    "image": null
   },
   {
    "heading": "多样餐桌选择，满足您的需求",
    "text": "",
    "image": null
   },
   {
    "heading": "灵活用餐，尽享可伸缩餐桌的便利",
    "text": "",
    "image": null
   },
   {
    "heading": "兼具美观与舒适的宜家餐椅餐凳",
    "text": "",
    "image": null
   },
   {
    "heading": "餐厅布置技巧",
    "text": "TRÖDEN 特鲁登 系列推出了全新的陶瓷桌面餐桌。高压陶瓷桌面坚固耐用，耐刮擦、防污渍、耐冷又耐热。 通过大批量生产和智能设计，把高品质变得更实惠。现在，用更少的预算，为你的餐厅增添更多缤纷的生活细节。 您倾向于传统还是现代风格？是两人、四人还是六人的餐桌？无论是聚餐、喝茶还是工作，餐桌都是家庭情感联结的核心。总有一款餐桌，能完美契合您的生活方式。",
    "image": null
   },
   {
    "heading": "餐桌布置的三种风格创意",
    "text": "",
    "image": null
   },
   {
    "heading": "打造更具个性的家居装饰",
    "text": "",
    "image": null
   },
   {
    "heading": "令日常晚餐更有仪式感的五个创意",
    "text": "",
    "image": null
   },
   {
    "heading": "餐厅布置小窍门和创意",
    "text": "",
    "image": null
   },
   {
    "heading": "如何为喜欢的花选择合适的花瓶",
    "text": "",
    "image": null
   },
   {
    "heading": "如何延长餐厅家具的使用寿命",
    "text": "如何通过简单的方法延长餐厅家具的使用寿命，确保多年使用仍保持时尚的外观和实用的功能。",
    "image": null
   }
  ],
  "links": [
   "/",
   "/cn/zh/cat/19145",
   "/cn/zh/cat/21825",
   "/cn/zh/cat/25219",
   "/cn/zh/cat/22659",
   "/cn/zh/cat/25222",
   "/cn/zh/cat/16244",
   "/cn/zh/cat/19141",
   "/cn/zh/cat/kt001",
   "/cn/zh/cat/20542",
   "/cn/zh/cat/de001",
   "/cn/zh/new/living room-news-pubb17d1057",
   "/cn/zh/p/30594033?artType=art",
   "/cn/zh/inspiration/detail/797ce61e-6e20-4686-ac4e-b0f0e079de0f?type=IMAGE"
  ]
 },
 {
  "url": "/cn/zh/rooms/childrens-room/",
  "family": "rooms",
  "title": "婴儿房和儿童房的家具、创意及其他设计灵感。",
  "h1": "婴儿和儿童房",
  "hero": "/images/pages/cn-zh-rooms-childrens-room/img-1.jpg",
  "sections": [
   {
    "heading": "让家的每个角落都藏着玩趣",
    "text": "",
    "image": null
   },
   {
    "heading": "更多家居灵感",
    "text": "",
    "image": null
   },
   {
    "heading": "让孩子安心玩耍的房间",
    "text": "",
    "image": null
   },
   {
    "heading": "富有趣味性的创意玩具",
    "text": "利乐宝玩具火车设计精巧，适合3岁以上儿童。它包含一个多彩的火车头和几节独特图案和颜色的货车。火车头和车厢通过磁性连接，方便幼儿拼装和拆卸，激发他们的创造力和操作能力。",
    "image": null
   },
   {
    "heading": "属于青少年自己的空间",
    "text": "",
    "image": null
   },
   {
    "heading": "两用办公学习桌",
    "text": "灵活的升降设计专为青少年打造的学习与休闲两用的场景，亦可搭配RELATERA 雷拉铁拉 配件，增添更多功能和储物空间",
    "image": null
   },
   {
    "heading": "安全舒适的婴儿产品",
    "text": "",
    "image": null
   },
   {
    "heading": "打造一个更适孩子的空间",
    "text": "",
    "image": null
   },
   {
    "heading": "安全环保的儿童产品",
    "text": "",
    "image": null
   },
   {
    "heading": "提供安全儿童产品",
    "text": "TROFAST 舒法特 系列",
    "image": null
   }
  ],
  "links": [
   "/",
   "/cn/zh/rooms/childrens-room/er-tong-shui-mian-he-shou-na-pub61221de8",
   "/cn/zh/rooms/childrens-room/kai-xin-wan-le-----wan-ju-xi-lie-pub310f8b0f",
   "/cn/zh/rooms/childrens-room/wei-bu-tong-jie-duan-hai-zi-men-she-ji-de-xue-xi-jiao-pub7e6ea468",
   "/cn/zh/rooms/childrens-room/wei-ying-er-de-cheng-chang-bao-jia-hu-hang-pub369a2f2f",
   "/cn/zh/new/let-your-home-come-out-and-play-pubc28e2323",
   "/cn/zh/rooms/childrens-room/gallery/",
   "/cn/zh/p/50266506?artType=art",
   "/cn/zh/p/39124617?artType=SPR",
   "/cn/zh/p/49226677?artType=spr",
   "/cn/zh/p/49555036?artType=spr",
   "/cn/zh/inspiration/detail/02a48390-1e22-4c2c-b2e3-dc2cc97e265e?type=IMAGE",
   "/cn/zh/cat/18738",
   "/cn/zh/cat/18706"
  ]
 },
 {
  "url": "/cn/zh/rooms/bathroom/",
  "family": "rooms",
  "title": "宜家浴室家居_宜家",
  "h1": "浴室",
  "hero": "/images/pages/cn-zh-rooms-bathroom/img-1.png",
  "sections": [
   {
    "heading": "TÄNNFORSEN 坦弗森 系列",
    "text": "",
    "image": null
   },
   {
    "heading": "TÄNNFORSEN 坦弗森 / ORRSJÖN 欧雪恩",
    "text": "洗脸池柜带门/深洗脸池/水龙头, 62x49x72 厘米",
    "image": null
   },
   {
    "heading": "TÄNNFORSEN 坦弗森",
    "text": "带门镜柜, 60x15x95 厘米",
    "image": null
   },
   {
    "heading": "TÄNNFORSEN 坦弗森 / RUTSJÖN 鲁特雪恩",
    "text": "洗脸池柜带门/洗脸池/水龙头, 82x49x74 厘米",
    "image": null
   },
   {
    "heading": "TÄNNFORSEN 坦弗森",
    "text": "带门镜柜, 80x15x95 厘米",
    "image": null
   },
   {
    "heading": "TÄNNFORSEN 坦弗森 / ORRSJÖN 欧雪恩",
    "text": "洗脸池柜带抽屉/洗脸池/水龙头, 102x49x69 厘米",
    "image": null
   },
   {
    "heading": "TÄNNFORSEN 坦弗森",
    "text": "带门镜柜, 100x15x95 厘米",
    "image": null
   },
   {
    "heading": "TÄNNFORSEN 坦弗森 / RUTSJÖN 鲁特雪恩",
    "text": "洗脸池柜带门/洗脸池/水龙头, 82x49x76 厘米",
    "image": null
   },
   {
    "heading": "TÄNNFORSEN 坦弗森",
    "text": "带门壁柜, 40x15x95 厘米",
    "image": null
   },
   {
    "heading": "TÄNNFORSEN 坦弗森",
    "text": "高柜带门, 40x35x195 厘米",
    "image": null
   },
   {
    "heading": "打造高品质的舒适卫浴环境",
    "text": "",
    "image": null
   }
  ],
  "links": [
   "/",
   "/cn/zh/cat/700450",
   "/cn/zh/cat/20804",
   "/cn/zh/search/products?q=浴室推车",
   "/cn/zh/cat/10555",
   "/cn/zh/search/products?q=马桶刷",
   "/cn/zh/cat/40690",
   "/cn/zh/cat/20723",
   "/cn/zh/cat/20724",
   "/cn/zh/cat/700170",
   "/cn/zh/cat/47358",
   "/cn/zh/cat/20490",
   "/cn/zh/cat/tl003",
   "/cn/zh/cat/10736"
  ]
 },
 {
  "url": "/cn/zh/rooms/hallway/",
  "family": "rooms",
  "title": "门厅灵感、家具等设计元素",
  "h1": "门厅：借助巧妙的储物方案营造温馨的入口通道",
  "hero": "/images/pages/cn-zh-rooms-hallway/img-1.jpg",
  "sections": [
   {
    "heading": "用风格统一的储物系列打造和谐门厅",
    "text": "你可以选择同一系列的家具，让各个储物设计风格统一。",
    "image": null
   },
   {
    "heading": "充分利用门厅的简单技巧",
    "text": "门厅不只是一个走廊通道，更是家的第一印象，是日常收纳的重要空间。我们提供丰富多样、实用又时尚的门厅解决方案，可以帮助你营造一个温馨的入户空间，并保持门厅整洁有序。从设计巧妙的鞋柜和衣帽架，到精致的装饰镜和舒适的长凳，我们提供各种必需之物，可助你充分利用空间、增强功能性，并为你的家居带来雅致的格调。利用这些富有启发性的创意，让每次进出家门都轻松自在。 这里不只是一个门厅，更承载着回家的期盼 这个门厅仿佛在说“欢迎回家！”",
    "image": null
   },
   {
    "heading": "查看完整的门厅创意图库",
    "text": "",
    "image": null
   },
   {
    "heading": "一起来保持家庭门厅井井有条！",
    "text": "",
    "image": null
   },
   {
    "heading": "简单的门厅壁橱创意",
    "text": "",
    "image": null
   },
   {
    "heading": "三个方法助你布置时尚温馨的狭小门厅",
    "text": "",
    "image": null
   },
   {
    "heading": "保持门厅整洁的七条鞋履收纳创意",
    "text": "",
    "image": null
   },
   {
    "heading": "将孩子放在首位的家庭门厅储物创意",
    "text": "",
    "image": null
   },
   {
    "heading": "巧妙时尚的狭小门厅储物创意",
    "text": "",
    "image": null
   },
   {
    "heading": "加入宜家俱乐部",
    "text": "加入会员，享受专属折扣。更多个性化家居灵感，让你的想法照进现实 查看更多",
    "image": null
   },
   {
    "heading": "加入宜家企业会员",
    "text": "加入企业会员，享受会员6大权益以及专属折扣。助力中小微企业共同成长。 查看更多",
    "image": null
   },
   {
    "heading": "常用链接",
    "text": "",
    "image": null
   }
  ],
  "links": [
   "/",
   "/cn/zh/rooms/hallway/gallery/all-natural-family-hallway-ideas-pubbbbda7d2",
   "/cn/zh/rooms/hallway/gallery/kid-friendly-hallway-ideas-that-work-for-all-ages-pubf157fb40",
   "/cn/zh/rooms/hallway/gallery/hallway-decorating-ideas-for-lasting-first-impressions-pub452174ad",
   "/cn/zh/rooms/hallway/gallery/a-hallway-that-shouts-welcome-home-and-means-it-pub75f6b8ea",
   "/cn/zh/rooms/hallway/gallery/a-bold-modern-hallway-on-a-budget-no-drill-needed-pube6cec945",
   "/cn/zh/rooms/hallway/gallery",
   "/cn/zh/cat/37894",
   "/cn/zh/p/platsa-pu-la-sa-kai-fang-shi-ge-jia-dan-yuan-bai-se-90452573",
   "/cn/zh/p/odger-ao-de-ge-yi-zi-mei-hei-se-30457314",
   "/cn/zh/cat/58618",
   "/cn/zh/cat/48956",
   "/cn/zh/p/plogfara-pu-lu-fa-la-fu-gai-chu-wu-he-2-jian-tao-dan-mi-se-80543215",
   "/cn/zh/p/snidad-si-ni-da-lan-teng-tiao-00394945"
  ]
 },
 {
  "url": "/cn/zh/rooms/home-office/",
  "family": "rooms",
  "title": "宜家书房和办公室-满足工作、学习和兴趣娱乐的各种需求",
  "h1": "书房和办公室",
  "hero": "/images/pages/cn-zh-rooms-home-office/img-1.png",
  "sections": [
   {
    "heading": "小空间，大作用！",
    "text": "",
    "image": null
   },
   {
    "heading": "小空间，大作用！",
    "text": "",
    "image": null
   },
   {
    "heading": "让学习办公游刃有余",
    "text": "",
    "image": null
   },
   {
    "heading": "光影变奏，点亮家的氛围感",
    "text": "灯光不只是照明，更是情绪的调色师。选一款合适的灯，让家中夜晚变得温暖又有故事，再搭配一些办公配件，家庭办公的氛围悄悄提升。",
    "image": null
   },
   {
    "heading": "MITTZON 米特丛 系列",
    "text": "",
    "image": null
   },
   {
    "heading": "适合不同空间和预算的电竞房布置创意",
    "text": "想要将你的电竞体验提升至更高级别？ 无论你喜欢时尚现代的外观还是舒适质朴的氛围，这些电竞房设计都可帮助你打造个性化的游戏天地。这些创意将舒适度、功能性和风格巧妙融合，可为你带来丰富灵感。",
    "image": null
   },
   {
    "heading": "家庭办公空间案例",
    "text": "",
    "image": null
   },
   {
    "heading": "一把高品质办公椅，跃升办公品质",
    "text": "",
    "image": null
   },
   {
    "heading": "家庭办公空间的实用指南",
    "text": "这款拉出式桌子造型紧凑，可轻松摆放在任何狭小角落里，展开后可满足你的各种创意项目和爱好需求。 小巧便携，需要用时又能提供宽敞桌面！ 这款拉出式桌子造型紧凑，可轻松摆放在任何狭小角落里，展开后可满足你的各种创意项目和爱好需求。 小巧便携，需要用时又能提供宽敞桌面！ 打破久坐僵局，唤醒办公活力，提升专注力，灵感随时迸发。",
    "image": null
   },
   {
    "heading": "查看更多家庭办公建议",
    "text": "",
    "image": null
   },
   {
    "heading": "为每一位家庭成员打造一片工作空间",
    "text": "",
    "image": null
   },
   {
    "heading": "打造符合人体工学的办公空间指南",
    "text": "",
    "image": null
   }
  ],
  "links": [
   "/",
   "/cn/zh/cat/20649",
   "/cn/zh/cat/20652",
   "/cn/zh/cat/10711",
   "/cn/zh/cat/10385",
   "/cn/zh/cat/10382",
   "/cn/zh/cat/20660",
   "/cn/zh/cat/20502",
   "/cn/zh/cat/10550",
   "/cn/zh/cat/10551",
   "/cn/zh/cat/10573",
   "/cn/zh/rooms/home-office/gallery/",
   "/cn/zh/inspiration/detail/8514724a-56b1-41e0-aad4-bf2e83be388b?type=IMAGE",
   "/cn/zh/inspiration/detail/9cc83ae8-45bd-47c7-85a9-f33136841773?type=IMAGE"
  ]
 },
 {
  "url": "/cn/zh/rooms/balcony/",
  "family": "rooms",
  "title": "探索阳台的无限潜力",
  "h1": "阳台",
  "hero": "/images/pages/cn-zh-rooms-balcony/img-1.jpg",
  "sections": [
   {
    "heading": "每个阳台都有无限的潜力",
    "text": "",
    "image": null
   },
   {
    "heading": "阳台推荐产品",
    "text": "",
    "image": null
   },
   {
    "heading": "SUNDSÖ 苏恩索",
    "text": "桌子和两折叠椅, 65 厘米",
    "image": null
   },
   {
    "heading": "KOLBJÖRN 科比约恩",
    "text": "搁架单元，室内/户外, 80x81 厘米",
    "image": null
   },
   {
    "heading": "TÄRNÖ 塔尔诺",
    "text": "",
    "image": null
   },
   {
    "heading": "OMAR 奥马尔",
    "text": "搁架单元, 92x36x94 厘米",
    "image": null
   },
   {
    "heading": "TÄRNÖ 塔尔诺",
    "text": "桌子，户外, 55x54 厘米",
    "image": null
   },
   {
    "heading": "ASKHOLMEN 阿霍蒙",
    "text": "",
    "image": null
   },
   {
    "heading": "NÄMMARÖ 耐玛瑞",
    "text": "",
    "image": null
   },
   {
    "heading": "NÄMMARÖ 耐玛瑞",
    "text": "桌子，户外, 75x63 厘米",
    "image": null
   },
   {
    "heading": "KOLBJÖRN 科比约恩",
    "text": "柜子 室内/户外, 80x81 厘米",
    "image": null
   },
   {
    "heading": "ASKHOLMEN 阿霍蒙",
    "text": "",
    "image": null
   }
  ],
  "links": [
   "/",
   "/cn/zh/cat/700350",
   "/cn/zh/cat/59249",
   "/cn/zh/cat/21958",
   "/cn/zh/cat/21957",
   "/cn/zh/cat/31787",
   "/cn/zh/cat/17897",
   "/cn/zh/cat/20602",
   "/cn/zh/cat/20601",
   "/cn/zh/cat/20609",
   "/cn/zh/rooms/balcony/gallery/",
   "/cn/zh/p/jostein-yue-si-tan-ge-jia-dan-yuan-shi-nei-hu-wai-bai-se-49437298",
   "/cn/zh/p/pinnig-pei-ni-ge-san-tou-gou-jia-hei-se-60329792",
   "/cn/zh/search/products?q=阳台"
  ]
 },
 {
  "url": "/cn/zh/rooms/outdoor/",
  "family": "rooms",
  "title": "用全新户外家具焕新户外空间",
  "h1": "户外",
  "hero": "/images/pages/cn-zh-rooms-outdoor/img-1.jpg",
  "sections": [
   {
    "heading": "阳台、庭院、户外空间创意图库",
    "text": "找到你梦想中的户外空间",
    "image": null
   },
   {
    "heading": "多样户外餐桌选择，满足您的需求",
    "text": "",
    "image": null
   },
   {
    "heading": "户外空间技巧和创意",
    "text": "找到你梦想中的户外空间 宁静葱郁的阳台，植物的乐园 可以晾晒衣物的舒适阳台",
    "image": "/images/pages/cn-zh-rooms-outdoor/img-2.jpg"
   },
   {
    "heading": "查看完整的户外创意图库",
    "text": "",
    "image": null
   },
   {
    "heading": "低成本的小阳台装饰方法",
    "text": "",
    "image": null
   },
   {
    "heading": "如何打造户外娱乐区",
    "text": "",
    "image": null
   },
   {
    "heading": "利用阳台储物解决方案清除杂乱、释放空间",
    "text": "",
    "image": null
   },
   {
    "heading": "户外灯具装饰创意",
    "text": "",
    "image": null
   },
   {
    "heading": "适合花园的模块化户外厨房创意",
    "text": "",
    "image": null
   },
   {
    "heading": "户外家具保养",
    "text": "",
    "image": null
   },
   {
    "heading": "规划庭院空间和选择户外家具",
    "text": "",
    "image": null
   },
   {
    "heading": "加入宜家俱乐部",
    "text": "加入会员，享受专属折扣。更多个性化家居灵感，让你的想法照进现实 查看更多",
    "image": null
   }
  ],
  "links": [
   "/",
   "/cn/zh/cat/700351",
   "/cn/zh/cat/700350",
   "/cn/zh/cat/21958",
   "/cn/zh/cat/21957",
   "/cn/zh/cat/17887",
   "/cn/zh/cat/700349",
   "/cn/zh/cat/17893",
   "/cn/zh/rooms/outdoor/gallery",
   "/cn/zh/rooms/outdoor/gallery/lv4-yi4-ying2-rao3-ning2-jing4-qing1-you1-de5-xiao3-yang2-tai2-pubf87b0a34",
   "/cn/zh/rooms/outdoor/gallery/shi4-he2-liang4-shai4-yi1-wu4-de5-xiao3-xing2-xiu1-xian2-yang2-tai2-pubc7fec744",
   "/cn/zh/rooms/outdoor/gallery/xian4-dai4-feng1-ge2-de5-xia4-ri4-hu4-wai4-yong4-can1-xiu1-xian2-qu1-pube2cf9987",
   "/cn/zh/rooms/outdoor/gallery/easy-garden-design-ideas-for-your-apartment-balcony-pub202b7ff9",
   "/cn/zh/rooms/outdoor/gallery/modern-outdoor-decorating-ideas-for-cosy-dinners-and-parties-pub8f74bf4a"
  ]
 },
 {
  "url": "/cn/zh/rooms/bedroom/gallery/",
  "family": "galleries",
  "title": "卧室灵感",
  "h1": "探索卧室灵感",
  "hero": "/images/pages/cn-zh-rooms-bedroom-gallery/img-1.png",
  "sections": [
   {
    "heading": "用深木色调营造宁静氛围",
    "text": "看起来也许像高级酒店，但其实是家。色彩协调统一的家具是营造这种宁静氛围的关键。每天晚上回到这间卧室，就像开始一次短暂的休假，让你尽情放松身心。",
    "image": null
   },
   {
    "heading": "更多往期展间",
    "text": "",
    "image": null
   },
   {
    "heading": "探访我们的本地家居案例",
    "text": "",
    "image": null
   },
   {
    "heading": "加入宜家俱乐部",
    "text": "加入会员，享受专属折扣。更多个性化家居灵感，让你的想法照进现实 查看更多",
    "image": null
   },
   {
    "heading": "加入宜家企业会员",
    "text": "加入企业会员，享受会员6大权益以及专属折扣。助力中小微企业共同成长。 查看更多",
    "image": null
   },
   {
    "heading": "常用链接",
    "text": "",
    "image": null
   },
   {
    "heading": "客户服务",
    "text": "",
    "image": null
   },
   {
    "heading": "关于宜家",
    "text": "",
    "image": null
   },
   {
    "heading": "宜家新闻",
    "text": "",
    "image": null
   },
   {
    "heading": "不知道如何搭配？",
    "text": "专业家居顾问为您提供免费的线上软装搭配服务",
    "image": null
   }
  ],
  "links": [
   "/",
   "/cn/zh/rooms/bedroom/gallery/tidy-bedroom-ideas-in-dark-wood-and-a-light-sense-pub804cf2e0",
   "/cn/zh/rooms/bedroom/gallery/make-your-bedroom-a-natural-and-personal-oasis-pubc65198fc",
   "/cn/zh/rooms/bedroom/gallery/a-teenagers-room-is-a-world-of-its-own-pubefb9da64",
   "/cn/zh/rooms/bedroom/gallery/a-first-home-that-can-last-forever-pub71c841e2",
   "/cn/zh/rooms/bedroom/gallery/your-first-own-home-with-room-for-everyone-you-know-pub9ed33410",
   "/cn/zh/rooms/bedroom/gallery/3D-room-pub9dda480a",
   "/cn/zh/rooms/bedroom/gallery/3D-room-pubac74b337",
   "/cn/zh/rooms/bedroom/gallery/checking-in-to-your-college-dorm-room-puba22dde68",
   "/cn/zh/rooms/bedroom/gallery/decorating-a-rental-room-heres-one-thats-full-of-personality-pub8f220f67",
   "/cn/zh/rooms/bedroom/gallery/shared-family-bedroom-ideas-with-room-for-everyone-and-their-things-pub3c656c58",
   "/cn/zh/rooms/bedroom/gallery/a-modern-eclectic-bedroom-with-space-for-your-dreams-pubd70320b6",
   "/cn/zh/rooms/bedroom/gallery/nature-inspired-interior-design-creates-a-lush-hideaway-pub17c53390",
   "/cn/zh/rooms/bedroom/gallery/a-vibrant-graphic-style-bedroom-that-works-as-hard-as-you-pub3f9d9511"
  ]
 },
 {
  "url": "/cn/zh/rooms/dining/gallery/",
  "family": "galleries",
  "title": "餐厅灵感",
  "h1": "满足日常生活所需的用餐区布置灵感",
  "hero": "/images/pages/cn-zh-rooms-dining-gallery/img-1.jpg",
  "sections": [
   {
    "heading": "加入宜家俱乐部",
    "text": "加入会员，享受专属折扣。更多个性化家居灵感，让你的想法照进现实 查看更多",
    "image": null
   },
   {
    "heading": "加入宜家企业会员",
    "text": "加入企业会员，享受会员6大权益以及专属折扣。助力中小微企业共同成长。 查看更多",
    "image": null
   },
   {
    "heading": "常用链接",
    "text": "",
    "image": null
   },
   {
    "heading": "客户服务",
    "text": "",
    "image": null
   },
   {
    "heading": "关于宜家",
    "text": "",
    "image": null
   },
   {
    "heading": "宜家新闻",
    "text": "",
    "image": null
   }
  ],
  "links": [
   "/",
   "/cn/zh/rooms/dining/gallery/versatile-dining-room-ideas-for-meals-and-moments-together-pubcedc88ba",
   "/cn/zh/rooms/dining/gallery/an-instagram-worthy-dining-room-pub1c2e3be9",
   "/cn/zh/rooms/dining/gallery/well-organised-and-flexible-family-dining-room-takes-the-enjoyment-from-kitchen-to-table-and-beyond-puba20af1dd",
   "/cn/zh/rooms/dining/gallery/flexible-and-compact-dining-room-transforms-from-workspace-to-dining-area-in-moments-pubcef6db61",
   "/cn/zh/rooms/dining/gallery/a-modern-scandinavian-dining-room-in-a-shared-student-home-pub68fa6fbc",
   "/cn/zh/rooms/dining/gallery/traditional-style-dining-room-for-family-gatherings-of-all-sizes-pub75a6d429",
   "/cn/zh/rooms/dining/gallery/shi4-he2-fan2-mang2-jia1-ting2-de5-si1-kan1-de5-na4-wei2-ya4-feng1-ge2-yong4-can1-qu1-bu4-zhi4-ling2-gan3-pub67e37afe",
   "/cn/zh/rooms/dining/gallery/da3-zao4-ge4-xing4-hua4-bu4-zhi4-xiao3-kong1-jian1-yong4-can1-qu1-ling2-gan3-pub9b1b0f46",
   "/cn/zh/rooms/dining/gallery/a-modern-scandinavian-dining-room-that-blends-with-the-living-area-pube78a108b",
   "/cn/zh/rooms/dining/gallery/xiao3-xiao3-jia1-ting2-yong4-can1-qu1-man3-zu2-yong4-can1-he2-qi2-ta1-xu1-qiu2-pub235f6008",
   "/cn/zh/rooms/dining/gallery/a-small-dining-room-with-a-big-heart-pub442c6ff3",
   "/cn/zh/rooms/dining/gallery/sliding-doors-and-a-round-table-a-small-smart-and-versatile-dining-room-pubbcedab0b",
   "/cn/zh/rooms/dining/gallery/a-small-cottage-style-dining-room-for-the-whole-family-pub571237d9"
  ]
 },
 {
  "url": "/cn/zh/rooms/home-office/gallery/",
  "family": "galleries",
  "title": "为工作、学习和爱好布置一个理想的角落",
  "h1": "工作、学习和爱好布置图库",
  "hero": "/images/pages/cn-zh-rooms-home-office-gallery/img-1.jpg",
  "sections": [
   {
    "heading": "加入宜家俱乐部",
    "text": "加入会员，享受专属折扣。更多个性化家居灵感，让你的想法照进现实 查看更多",
    "image": null
   },
   {
    "heading": "加入宜家企业会员",
    "text": "加入企业会员，享受会员6大权益以及专属折扣。助力中小微企业共同成长。 查看更多",
    "image": null
   },
   {
    "heading": "常用链接",
    "text": "",
    "image": null
   },
   {
    "heading": "客户服务",
    "text": "",
    "image": null
   },
   {
    "heading": "关于宜家",
    "text": "",
    "image": null
   },
   {
    "heading": "宜家新闻",
    "text": "",
    "image": null
   }
  ],
  "links": [
   "/",
   "/cn/zh/rooms/home-office/gallery/a-shared-teens-room-built-for-two-pubc769f488",
   "/cn/zh/rooms/home-office/gallery/a-wfh-setup-that-doesnt-get-in-the-way-of-living-pubd42869f4",
   "/cn/zh/rooms/home-office/gallery/student-studio-space-saving-ideas-that-leave-room-for-more-pub4392b964",
   "/cn/zh/rooms/home-office/gallery/yi3-chong1-man3-huo2-li4-de5-bin1-fen1-feng1-ge2-da3-zao4-ge4-xing4-hua4-de5-gong1-zuo4-kong1-jian1-pub3ba6556c",
   "/cn/zh/rooms/home-office/gallery/xian4-dai4-gong1-ye4-feng1-de5-chuang4-yi4-kong1-jian1-pub911625d6",
   "/cn/zh/rooms/home-office/gallery/one-dorm-room-two-expressions-pub7750d15f",
   "/cn/zh/rooms/home-office/gallery/a-calm-focus-area-thats-one-with-the-living-room-pubebdf6044",
   "/cn/zh/rooms/home-office/gallery/a-room-brimming-with-creativity-pub742bbae0",
   "/cn/zh/rooms/home-office/gallery/teen-living-in-a-cosy-space-with-a-sense-of-musicality-pubb94026bc",
   "/cn/zh/rooms/home-office/gallery/an-earthy-living-space-that-unites-productivity-and-relaxation-pub1d8b1f5a",
   "/cn/zh/rooms/home-office/gallery/small-storage-ideas-across-the-home-pub8d952fe7",
   "/cn/zh/rooms/home-office/gallery/a-traditional-style-home-office-thats-a-game-room-too-pub78184b28",
   "/cn/zh/rooms/home-office/gallery/the-refined-gamers-den-a-hand-picked-home-with-a-punk-soul-pubc42ec667"
  ]
 },
 {
  "url": "/cn/zh/rooms/living-room/gallery/",
  "family": "galleries",
  "title": "客厅灵感图库",
  "h1": "符合个人风格与日常生活需求的客厅设计灵感",
  "hero": "/images/pages/cn-zh-rooms-living-room-gallery/img-1.png",
  "sections": [
   {
    "heading": "充满大胆色彩混搭的斯堪的纳维亚风格客厅",
    "text": "把小客厅当作一块空白画布，不同材料和色彩的混搭，如同是用不同乐器演奏一首美妙的交响乐。白色背景出色衬托明亮色调和浅色木材的自然质感，营造出与你品味和个性相契合的整体外观。",
    "image": null
   },
   {
    "heading": "融合斯堪的纳维亚传统与现代生活的起居室",
    "text": "欢迎来到这个父母和青少年孩子都喜欢的温馨起居室。在这里，每个人都有属于自己的空间，可以做自己想做的事——甚至可以招待客人留宿。配色及天然材料尽显斯堪的纳维亚传统特色，同时又融入了现代元素。",
    "image": null
   },
   {
    "heading": "加入宜家俱乐部",
    "text": "加入会员，享受专属折扣。更多个性化家居灵感，让你的想法照进现实 查看更多",
    "image": null
   },
   {
    "heading": "加入宜家企业会员",
    "text": "加入企业会员，享受会员6大权益以及专属折扣。助力中小微企业共同成长。 查看更多",
    "image": null
   },
   {
    "heading": "常用链接",
    "text": "",
    "image": null
   },
   {
    "heading": "客户服务",
    "text": "",
    "image": null
   },
   {
    "heading": "关于宜家",
    "text": "",
    "image": null
   },
   {
    "heading": "宜家新闻",
    "text": "",
    "image": null
   },
   {
    "heading": "不知道如何搭配？",
    "text": "专业家居顾问为您提供免费的线上软装搭配服务",
    "image": null
   }
  ],
  "links": [
   "/",
   "/cn/zh/landing-page/cn--zh--b941f320bd3811efa9398bb9e44cf74f",
   "/cn/zh/landing-page/cn--zh--33dc9780cd0511efa9398bb9e44cf74f",
   "/cn/zh/rooms/living-room/gallery/an-instagram-worthy-living-room-thats-small-modern-and-multifunctional-pub513157a0",
   "/cn/zh/rooms/living-room/gallery/a-small-functional-living-room-with-space-for-a-creative-family-pub5b89ae17",
   "/cn/zh/rooms/living-room/gallery/step-into-a-tiny-first-apartment-pub79905ef5",
   "/cn/zh/rooms/living-room/gallery/ren2-ren2-ge4-de2-qi2-le4-de5-xian4-dai4-jia1-ting2-ke4-ting1-pub347efa81",
   "/cn/zh/rooms/living-room/gallery/an4-ni3-xin1-yi4-she4-ji4-de5-si1-kan1-de5-na4-wei2-ya4-feng1-ge2-xiao3-ke4-ting1-puba678efaf",
   "/cn/zh/rooms/living-room/gallery/a-modern-living-room-with-a-timeless-look-for-your-cosy-mingles-pubbba74b5e",
   "/cn/zh/rooms/living-room/gallery/a-modern-urban-living-room-with-round-the-clock-comfort-pube7cc04db",
   "/cn/zh/rooms/living-room/gallery/an-airy-modern-style-living-room-to-feel-pampered-in-pub4eed6033",
   "/cn/zh/rooms/living-room/gallery/a-traditional-living-room-with-space-for-everyone-pub66e69d32",
   "/cn/zh/rooms/living-room/gallery/earthy-colours-set-the-mood-in-a-small-flexible-living-room-pub8ae45da5",
   "/cn/zh/rooms/living-room/gallery/a-modern-scandi-living-room-small-but-family-sized-pub58880756"
  ]
 },
 {
  "url": "/cn/zh/rooms/childrens-room/gallery/",
  "family": "galleries",
  "title": "儿童房灵感图库",
  "h1": "满足各阶段成长需求的儿童房设计灵感",
  "hero": "/images/pages/cn-zh-rooms-childrens-room-gallery/img-1.jpg",
  "sections": [
   {
    "heading": "加入宜家俱乐部",
    "text": "加入会员，享受专属折扣。更多个性化家居灵感，让你的想法照进现实 查看更多",
    "image": null
   },
   {
    "heading": "加入宜家企业会员",
    "text": "加入企业会员，享受会员6大权益以及专属折扣。助力中小微企业共同成长。 查看更多",
    "image": null
   },
   {
    "heading": "常用链接",
    "text": "",
    "image": null
   },
   {
    "heading": "客户服务",
    "text": "",
    "image": null
   },
   {
    "heading": "关于宜家",
    "text": "",
    "image": null
   },
   {
    "heading": "宜家新闻",
    "text": "",
    "image": null
   }
  ],
  "links": [
   "/",
   "/cn/zh/rooms/childrens-room/gallery/one-shared-childrens-bedroom-multiple-worlds-puba434d1c3",
   "/cn/zh/rooms/childrens-room/gallery/is-it-real-or-imagination-its-lillabo-really-the-best-kids-imagination-toys-pub0e6bd8e7",
   "/cn/zh/rooms/childrens-room/gallery/a-small-family-bedroom-with-lots-of-ideas-for-sharing-space-harmoniously-pube9a6a215",
   "/cn/zh/rooms/childrens-room/gallery/my-first-own-room-pubfb931117",
   "/cn/zh/rooms/childrens-room/gallery/gai1-an1-jing4-xia4-lai2-le5-pub3ed84ac3",
   "/cn/zh/rooms/childrens-room/gallery/everyday-life-blossoms-in-a-rustic-scandinavian-bedroom-pub4ce65ba1",
   "/cn/zh/rooms/childrens-room/gallery/creating-a-calming-bedroom-for-kids-in-your-own-room-pub9b180c0d",
   "/cn/zh/rooms/childrens-room/gallery/a-childrens-bedroom-that-would-make-any-grown-up-jealous-pub76d35d62",
   "/cn/zh/rooms/childrens-room/gallery/fun-bedroom-ideas-for-kids-full-of-ideas-of-their-own-pubacb5db97",
   "/cn/zh/rooms/childrens-room/gallery/a-scandi-style-kids-room-that-grows-up-with-your-child-puba01e0d6d",
   "/cn/zh/rooms/childrens-room/gallery/a-scandinavian-childrens-room-with-space-for-fun-and-sleep-times-two-pube2bf7db7",
   "/cn/zh/rooms/childrens-room/gallery/a-fun-colourful-room-thats-organised-to-suit-kids-pub9132ebfd",
   "/cn/zh/rooms/childrens-room/gallery/a-futuristic-dream-room-that-works-in-the-real-world-pub9b46068f"
  ]
 },
 {
  "url": "/cn/zh/rooms/hallway/gallery/",
  "family": "galleries",
  "title": "门厅灵感图库",
  "h1": "温馨的门厅设计，营造回家仪式感",
  "hero": "/images/pages/cn-zh-rooms-hallway-gallery/img-1.jpg",
  "sections": [
   {
    "heading": "加入宜家俱乐部",
    "text": "加入会员，享受专属折扣。更多个性化家居灵感，让你的想法照进现实 查看更多",
    "image": null
   },
   {
    "heading": "加入宜家企业会员",
    "text": "加入企业会员，享受会员6大权益以及专属折扣。助力中小微企业共同成长。 查看更多",
    "image": null
   },
   {
    "heading": "常用链接",
    "text": "",
    "image": null
   },
   {
    "heading": "客户服务",
    "text": "",
    "image": null
   },
   {
    "heading": "关于宜家",
    "text": "",
    "image": null
   },
   {
    "heading": "宜家新闻",
    "text": "",
    "image": null
   }
  ],
  "links": [
   "/",
   "/cn/zh/rooms/hallway/gallery/kid-friendly-hallway-ideas-that-work-for-all-ages-pubf157fb40",
   "/cn/zh/rooms/hallway/gallery/all-natural-family-hallway-ideas-pubbbbda7d2",
   "/cn/zh/rooms/hallway/gallery/hallway-decorating-ideas-for-lasting-first-impressions-pub452174ad",
   "/cn/zh/rooms/hallway/gallery/a-hallway-that-shouts-welcome-home-and-means-it-pub75f6b8ea",
   "/cn/zh/rooms/hallway/gallery/no-hallway-no-problem-make-an-entrance-in-relaxed-style-pub4e5ffb98",
   "/cn/zh/rooms/hallway/gallery/a-bold-modern-hallway-on-a-budget-no-drill-needed-pube6cec945",
   "/cn/zh/rooms/hallway/gallery/a-warm-and-space-effective-hallway-thats-full-of-character-pub6342ec76",
   "/cn/zh/rooms/hallway/gallery/a-striking-nature-inspired-entrance-with-greenery-that-pops-pub7f622719",
   "/cn/zh/rooms/hallway/gallery/a-super-small-scandi-hallway-with-a-playful-style-and-smart-storage-pubd9a65d47",
   "/cn/zh/rooms/hallway/gallery/an-elegant-welcoming-hallway-that-hides-plenty-of-storage-pub90b614c6",
   "/cn/zh/rooms/hallway/gallery/a-small-contemporary-hallway-filled-with-family-storage-pubd7bb3898",
   "/cn/zh/rooms/hallway/gallery/a-traditional-hallway-for-kids-parents-and-grandma-too-pube1e376c8",
   "/cn/zh/rooms/hallway/gallery/a-modern-hallway-that-the-kids-will-love-too-pubadb6452e"
  ]
 },
 {
  "url": "/cn/zh/rooms/kitchen/gallery/",
  "family": "galleries",
  "title": "厨房灵感图库",
  "h1": "厨房图库",
  "hero": null,
  "sections": [
   {
    "heading": "加入宜家俱乐部",
    "text": "加入会员，享受专属折扣。更多个性化家居灵感，让你的想法照进现实 查看更多",
    "image": null
   },
   {
    "heading": "加入宜家企业会员",
    "text": "加入企业会员，享受会员6大权益以及专属折扣。助力中小微企业共同成长。 查看更多",
    "image": null
   },
   {
    "heading": "常用链接",
    "text": "",
    "image": null
   },
   {
    "heading": "客户服务",
    "text": "",
    "image": null
   },
   {
    "heading": "关于宜家",
    "text": "",
    "image": null
   },
   {
    "heading": "宜家新闻",
    "text": "",
    "image": null
   }
  ],
  "links": [
   "/",
   "/cn/zh/landing-page/cn--zh--e9d6538404cb4dd6bb5a8e9f744c6920?productIds=&topProductFullIds=&assemblyProductFullIds=&utm_source=&utm_medium=&utm_campaign=&utm_content=&utm_term=&web_new=",
   "/cn/zh/landing-page/cn--zh--e856515546054ac28b0b6844659eb3af?productIds=&topProductFullIds=&assemblyProductFullIds=&utm_source=&utm_medium=&utm_campaign=&utm_content=&utm_term=&web_new=",
   "/cn/zh/landing-page/cn--zh--96e29462e5cc52ea97c3ff1054ad5a19?productIds=&topProductFullIds=&assemblyProductFullIds=&utm_source=&utm_medium=&utm_campaign=&utm_content=&utm_term=&web_new=",
   "/cn/zh/landing-page/cn--zh--256406b31966445a82bc38ef3a069406?productIds=&topProductFullIds=&assemblyProductFullIds=&utm_source=&utm_medium=&utm_campaign=&utm_content=&utm_term=&web_new=",
   "/cn/zh/landing-page/cn--zh--65c936f1ca5a42fe91e47639314c8829?productIds=&topProductFullIds=&assemblyProductFullIds=&utm_source=&utm_medium=&utm_campaign=&utm_content=&utm_term=&web_new=",
   "/cn/zh/rooms/kitchen/gallery/a-modern-mediterranean-kitchen-filled-with-warmth-and-tradition-pub452bb7ec",
   "/cn/zh/rooms/kitchen/gallery/a-well-integrated-kitchen-for-the-large-family-that-moves-to-the-rhythm-of-family-life-pub7e60807a",
   "/cn/zh/rooms/kitchen/gallery/small-studio-apartment-kitchen-that-blends-functionality-with-tranquility-pub458af826",
   "/cn/zh/rooms/kitchen/gallery/compact-kitchen-for-your-multigenerational-family-pub4cb7f8e4",
   "/cn/zh/rooms/kitchen/gallery/a-small-kitchen-made-big-with-space-saving-ideas-pub07ee0c2d",
   "/cn/zh/rooms/kitchen/gallery/want-more-space-for-cooking-playing-and-chilling-pub46525618",
   "/cn/zh/rooms/kitchen/gallery/a-minimalist-kitchen-with-an-open-and-welcoming-air-pub8369c640",
   "/cn/zh/rooms/kitchen/gallery/a-small-black-and-beige-kitchen-with-an-open-feel-pub6f14c4ba"
  ]
 },
 {
  "url": "/cn/zh/rooms/bathroom/gallery/",
  "family": "galleries",
  "title": "浴室布置灵感",
  "h1": "兼顾美观性和实用性的浴室设计灵感",
  "hero": "/images/pages/cn-zh-rooms-bathroom-gallery/img-1.jpg",
  "sections": [
   {
    "heading": "加入宜家俱乐部",
    "text": "加入会员，享受专属折扣。更多个性化家居灵感，让你的想法照进现实 查看更多",
    "image": null
   },
   {
    "heading": "加入宜家企业会员",
    "text": "加入企业会员，享受会员6大权益以及专属折扣。助力中小微企业共同成长。 查看更多",
    "image": null
   },
   {
    "heading": "常用链接",
    "text": "",
    "image": null
   },
   {
    "heading": "客户服务",
    "text": "",
    "image": null
   },
   {
    "heading": "关于宜家",
    "text": "",
    "image": null
   },
   {
    "heading": "宜家新闻",
    "text": "",
    "image": null
   }
  ],
  "links": [
   "/",
   "/cn/zh/rooms/bathroom/gallery/shared-bathroom-design-ideas-that-work-for-all-ages-pubee8c2069",
   "/cn/zh/rooms/bathroom/gallery/a-modern-bathroom-refresh-for-storage-galore-pubca730c65",
   "/cn/zh/rooms/bathroom/gallery/a-timeless-easy-to-tidy-half-bathroom-pub4cb1c517",
   "/cn/zh/rooms/bathroom/gallery/a-bathroom-in-earthy-tones-with-dark-contrasts-pub8fee5d15",
   "/cn/zh/rooms/bathroom/gallery/a-cosy-and-small-spa-bathroom-pub4cbb71ae",
   "/cn/zh/rooms/bathroom/gallery/a-small-bathroom-that-will-lift-your-spirits-pubd98f229e",
   "/cn/zh/rooms/bathroom/gallery/a-colourful-and-flexible-bathroom-designed-for-busy-families-pub164aa5a6",
   "/cn/zh/rooms/bathroom/gallery/a-practical-yet-stylish-bathroom-for-the-whole-family-pub85d91f4b",
   "/cn/zh/rooms/bathroom/gallery/a-sophisticated-modern-bathroom-retreat-with-rich-tones-pub8173df5d",
   "/cn/zh/rooms/bathroom/gallery/an-elegant-bathroom-with-a-laidback-luxury-feel-pubc3923d16",
   "/cn/zh/rooms/bathroom/gallery/a-small-japandi-style-bathroom-in-perfect-harmony-pub48a1ef75",
   "/cn/zh/rooms/bathroom/gallery/a-small-japandi-style-bathroom-in-perfect-harmony-pub2c008c50",
   "/cn/zh/rooms/bathroom/gallery/this-traditional-bathroom-is-a-place-for-peaceful-wellbeing-pub9c70daa1"
  ]
 },
 {
  "url": "/cn/zh/rooms/outdoor/gallery/",
  "family": "galleries",
  "title": "户外布置灵感图库",
  "h1": "户外图库",
  "hero": "/images/pages/cn-zh-rooms-outdoor-gallery/img-1.jpg",
  "sections": [
   {
    "heading": "加入宜家俱乐部",
    "text": "加入会员，享受专属折扣。更多个性化家居灵感，让你的想法照进现实 查看更多",
    "image": null
   },
   {
    "heading": "加入宜家企业会员",
    "text": "加入企业会员，享受会员6大权益以及专属折扣。助力中小微企业共同成长。 查看更多",
    "image": null
   },
   {
    "heading": "常用链接",
    "text": "",
    "image": null
   },
   {
    "heading": "客户服务",
    "text": "",
    "image": null
   },
   {
    "heading": "关于宜家",
    "text": "",
    "image": null
   },
   {
    "heading": "宜家新闻",
    "text": "",
    "image": null
   }
  ],
  "links": [
   "/",
   "/cn/zh/rooms/outdoor/gallery/an-ordinary-balcony-transformed-into-a-maximalist-sanctuary-pub30b5ef40",
   "/cn/zh/rooms/outdoor/gallery/the-joys-of-growing-a-spring-garden-pub2591a89d",
   "/cn/zh/rooms/outdoor/gallery/for-the-green-spirit-in-all-of-us-a-lush-balcony-retreat-pub5132e3c6",
   "/cn/zh/rooms/outdoor/gallery/a-modern-outdoor-space-turned-into-an-elegant-family-zone-all-year-round-pub1c586b85",
   "/cn/zh/rooms/outdoor/gallery/shi4-he2-liang4-shai4-yi1-wu4-de5-xiao3-xing2-xiu1-xian2-yang2-tai2-pubc7fec744",
   "/cn/zh/rooms/outdoor/gallery/lv4-yi4-ying2-rao3-ning2-jing4-qing1-you1-de5-xiao3-yang2-tai2-pubf87b0a34",
   "/cn/zh/rooms/outdoor/gallery/xian4-dai4-feng1-ge2-de5-xia4-ri4-hu4-wai4-yong4-can1-xiu1-xian2-qu1-pube2cf9987",
   "/cn/zh/rooms/outdoor/gallery/easy-garden-design-ideas-for-your-apartment-balcony-pub202b7ff9",
   "/cn/zh/rooms/outdoor/gallery/modern-outdoor-decorating-ideas-for-cosy-dinners-and-parties-pub8f74bf4a",
   "/cn/zh/rooms/outdoor/gallery/a-cosy-family-patio-with-rustic-outdoor-decor-ideas-pub216a2745",
   "/cn/zh/rooms/outdoor/gallery/a-traditional-style-outdoor-space-with-a-complete-modern-kitchen-pub06c4e113",
   "/cn/zh/rooms/outdoor/gallery/a-small-urban-balcony-turns-into-a-modern-sanctuary-puba1ba318f",
   "/cn/zh/rooms/outdoor/gallery/a-scandinavian-inspired-outdoor-space-that-is-all-about-enjoying-the-season-pub98710137"
  ]
 },
 {
  "url": "/cn/zh/ideas/rooms-inspiration/",
  "family": "ideas",
  "title": "房间灵感",
  "h1": "不同房间的不同灵感",
  "hero": null,
  "sections": [
   {
    "heading": "在实际场景中探索我们的产品",
    "text": "看看家中各个空间的宜家产品，寻找创意灵感和布置技巧：",
    "image": null
   },
   {
    "heading": "针对家中每个房间提供的巧妙提示和技巧",
    "text": "了解有关的装备、提示和DIY创意，掌握组合和打造舒适空间的妙招",
    "image": null
   },
   {
    "heading": "加入宜家俱乐部",
    "text": "加入会员，享受专属折扣。更多个性化家居灵感，让你的想法照进现实 查看更多",
    "image": null
   },
   {
    "heading": "加入宜家企业会员",
    "text": "加入企业会员，享受会员6大权益以及专属折扣。助力中小微企业共同成长。 查看更多",
    "image": null
   },
   {
    "heading": "常用链接",
    "text": "",
    "image": null
   },
   {
    "heading": "客户服务",
    "text": "",
    "image": null
   },
   {
    "heading": "关于宜家",
    "text": "",
    "image": null
   },
   {
    "heading": "宜家新闻",
    "text": "",
    "image": null
   }
  ],
  "links": [
   "/",
   "/cn/zh/rooms/living-room/gallery/",
   "/cn/zh/rooms/bedroom/gallery/",
   "/cn/zh/rooms/bathroom/gallery/",
   "/cn/zh/rooms/hallway/gallery/",
   "/cn/zh/rooms/dining/gallery/",
   "/cn/zh/rooms/kitchen/gallery/",
   "/cn/zh/rooms/childrens-room/gallery/",
   "/cn/zh/rooms/home-office/gallery/",
   "/cn/zh/rooms/outdoor/gallery/",
   "/cn/zh/ikea-business/gallery/",
   "/cn/zh/rooms/living-room/how-to/",
   "/cn/zh/rooms/bedroom/how-to/",
   "/cn/zh/rooms/outdoor/how-to/"
  ]
 },
 {
  "url": "/cn/zh/ideas/curated-by-me/",
  "family": "ideas",
  "title": "我的艺术展",
  "h1": "我的艺术展",
  "hero": "/images/pages/cn-zh-ideas-curated-by-me/img-1.jpg",
  "sections": [
   {
    "heading": "米兰设计周 x The Creatives",
    "text": "每个人，每个家，乃至世事万物都有自己的风格和外观。一起欣赏令人惊喜、有趣且迷人的多元风格和作品，感受艺术家们的鲜活个性。从不拘一格的几何图案、日式设计到极简主义，各有风格。 一起来看看我们的共创艺术家如何通过精心挑选的颜色、材料和物品，生动展现他们各自的风格，为所有热爱居家生活的人带来创意灵感。 强烈的红色调和空间中脱颖而出的物体充分地体现了Rea的风格。独树一帜的鲜明艺术气息。",
    "image": null
   },
   {
    "heading": "红色小夜曲",
    "text": "强烈的红色调和空间中脱颖而出的物体充分地体现了Rea的风格。独树一帜的鲜明艺术气息。",
    "image": null
   },
   {
    "heading": "粉红狂想曲",
    "text": "Chiamamifaro的名字和她的风格一样，都是一座灯塔。她年轻而自信，她的风格融合了宽松的男装与发梢上的一抹粉红色。",
    "image": null
   },
   {
    "heading": "阳光在混凝土上舞蹈",
    "text": "日本舞者Kyoka的特色在于动作、形态和引人注目的节奏。她融合了男性和女性的力量，在任何城市场景中都是一道耀眼的光芒。",
    "image": null
   },
   {
    "heading": "引人注目的蓝色还是雪白色？",
    "text": "Niveo的名字意为“洁白如雪”，但在他的艺术展的调色板中，深沉而富有情调的蓝色占据了中心位置。作为个人和表演者，他很友善、年轻且平易近人。然而，他的艺术展和他演唱的歌曲一样，深邃而广阔。",
    "image": null
   },
   {
    "heading": "复古怀旧风",
    "text": "设计专业的学生Izzy像是一只变色龙。今天，她的造型是鲜明的哥特风，但明天，就可能变成了邻家女孩。她是一个活在现代生活中的老灵魂。",
    "image": null
   },
   {
    "heading": "从其他家居风格中获取灵感，找到你的理想风格",
    "text": "",
    "image": null
   },
   {
    "heading": "继续阅读，获取更多技巧和灵感",
    "text": "每个人，每个家，乃至世事万物都有自己的风格和外观。一起欣赏令人惊喜、有趣且迷人的多元风格和作品，感受艺术家们的鲜活个性。从不拘一格的几何图案、日式设计到极简主义，各有风格。 一起来看看我们的共创艺术家如何通过精心挑选的颜色、材料和物品，生动展现他们各自的风格，为所有热爱居家生活的人带来创意灵感。 强烈的红色调和空间中脱颖而出的物体充分地体现了Rea的风格。独树一帜的鲜明艺术气息。",
    "image": null
   },
   {
    "heading": "浏览更多家居风格",
    "text": "来探索真正彰显你个性的风格吧。从经典隽永到时尚创新，丰富多样的风格任你探索。",
    "image": null
   },
   {
    "heading": "浏览我们按房间分类的灵感图库",
    "text": "今天是厨房，明天是起居室，下周还能变成卧室。查看针对每个房间提供的灵感创意和巧妙提示及技巧：",
    "image": null
   },
   {
    "heading": "在收纳中展示自我",
    "text": "以真实家庭真实人物的真实收纳需求和梦想为灵感，讲述真实的故事。",
    "image": null
   },
   {
    "heading": "家居环境参观之旅",
    "text": "探索宜家室内设计师独家设计的完整家装方案。",
    "image": null
   }
  ],
  "links": [
   "/",
   "/cn/zh/ideas/curated-by-me/serenades-of-red-pub9d03d6b7",
   "/cn/zh/ideas/curated-by-me/rhapsody-in-pink-pub07658000",
   "/cn/zh/ideas/curated-by-me/sunshine-bouncing-off-concrete-pub976f8a02",
   "/cn/zh/ideas/curated-by-me/groovy-blues-or-snowy-white-pub73b02643",
   "/cn/zh/ideas/curated-by-me/retro-revival-pub9131795e",
   "/cn/zh/ideas/curated-by-me/gothic-romance-home-decor-with-gold-and-black-accents-pubcd2ab081",
   "/cn/zh/ideas/curated-by-me/lovely-pastels-and-natural-tones-in-a-home-decor-inspired-by-travels-around-the-world-pub6959e401",
   "/cn/zh/ideas/curated-by-me/a-vibrant-colourful-home-decor-embracing-life-and-seasonal-changes-pubf034f672",
   "/cn/zh/ideas/curated-by-me/gorgeously-green-home-accessories-with-charming-linocut-prints-pub87dc6c00",
   "/cn/zh/ideas/curated-by-me/artisan-home-decor-filled-with-beautiful-handcrafted-natural-materials-pubc2a2f054",
   "/cn/zh/ideas/curated-by-me/colourful-vibrant-and-eclectic-home-decor-ideas-pub8c1695eb",
   "/cn/zh/ideas/curated-by-me/black-and-white-with-an-element-of-colourful-chaos-pubd1779f29",
   "/cn/zh/ideas/curated-by-me/organic-shapes-earthy-colours-and-geometric-patterns-pubd6d8a514"
  ]
 },
 {
  "url": "/cn/zh/ideas/ikea-plus-you/",
  "family": "ideas",
  "title": "一起宜家",
  "h1": "一起宜家",
  "hero": "/images/pages/cn-zh-ideas-ikea-plus-you/img-1.jpg",
  "sections": [
   {
    "heading": "他们的家",
    "text": "走进宜家粉丝的家，汇集多元化的家装灵感，展现个性化的生活方式。",
    "image": null
   },
   {
    "heading": "宜家去你家",
    "text": "由宜家设计师亲自参与，以探寻当代人对家与生活的真实态度为切入点，洞察屋主需求，提供个性化的家居解决方案，化解生活难题，打造理想之家。",
    "image": null
   },
   {
    "heading": "小改理想家",
    "text": "聚焦于小空间和小预算的改造，满足局部功能需求，同时焕新家居风格，打造实用与美观兼具的居住空间。",
    "image": null
   },
   {
    "heading": "加入宜家俱乐部",
    "text": "加入会员，享受专属折扣。更多个性化家居灵感，让你的想法照进现实 查看更多",
    "image": null
   },
   {
    "heading": "加入宜家企业会员",
    "text": "加入企业会员，享受会员6大权益以及专属折扣。助力中小微企业共同成长。 查看更多",
    "image": null
   },
   {
    "heading": "常用链接",
    "text": "",
    "image": null
   },
   {
    "heading": "客户服务",
    "text": "",
    "image": null
   },
   {
    "heading": "关于宜家",
    "text": "",
    "image": null
   },
   {
    "heading": "宜家新闻",
    "text": "",
    "image": null
   }
  ],
  "links": [
   "/",
   "/cn/zh/ideas/ikea-plus-you/bei-piao-nian-ban-jia-ci-xiao-yu-suan-ye-neng-zhu-chu-jia-de-wei-dao-pubf07e92b9",
   "/cn/zh/ideas/ikea-plus-you/zhong-nv-bu-jiao-lv-jie-jie-bao-gai-jing-zhuang-fang-ba-ri-zi-guo-cheng-xin-zhi-suo-xiang-puba9c5594d",
   "/cn/zh/ideas/ikea-plus-you/zhong-nv-bu-jiao-lv-jie-jie-bao-gai-jing-zhuang-fang-ba-ri-zi-guo-cheng-xin-zhi-suo-xiang-pub10971c33",
   "/cn/zh/ideas/ikea-plus-you/ta-yong-fa-shi-feng-gong-gong-qu-jia-cha-ji-feng-yue-ji-qu-shi-xian-le-san-dai-ren-de-qi-miao-ping-heng--pub70dbdf1f",
   "/cn/zh/ideas/ikea-plus-you/she-ji-shi-du-jing-yan-de-fan-gu-shi-zhuang-xiu-rang-ta-shi-xian-le-zhen-zheng-de-zi-you-he-qing-song--pub7bbe429e",
   "/cn/zh/ideas/ikea-plus-you/-shi-ting-gai-shi-tu-sha--pub68ab2add",
   "/cn/zh/ideas/ikea-plus-you/-hun-an-lao-fang-zheng-rong-shi-bao-gai-hui-you-dong-xian-rang-jia-da-le-bei--pub0507d2ad",
   "/cn/zh/ideas/ikea-plus-you/-lao-po-xiao-bao-gai-se-cai-xiao-wu-bu-hun-zhu-yi-de-ta-guo-de-chao-kuai-huo--puba778a4c0",
   "/cn/zh/ideas/ikea-plus-you/mu-nv-er-ren-tong-zhu-yue-ji-zi-you-quan-du-you-ping-zhuang-xia-suo-you-ai--pubd26cd260",
   "/cn/zh/ideas/ikea-plus-you/zai-yong-you-pen-zhi-wu-de-jia-li-ji-qu-zhi-yu-de-li-liang-ba-zi-ji-dang-lv-zhi-lai-yang--pub86c7e0da",
   "/cn/zh/ideas/ikea-plus-you/yuan-lai-i-ren-de-xiao-jia-neng-zhuang-xia-zheng-ge-duo-ba-an-shi-jie-pub78b84c16",
   "/cn/zh/ideas/ikea-plus-you/zuan-yan-nian-ta-zong-jie-de-jia-zhuang-jing-rang-ren-shao-zou-hen-duo-wan-lu-pub10a45893",
   "/cn/zh/ideas/ikea-plus-you/zuan-yan-nian-ta-zong-jie-de-jia-zhuang-jing-rang-ren-shao-zou-hen-duo-wan-lu-pubb982ae46"
  ]
 },
 {
  "url": "/cn/zh/ideas/tips-for-more-sustainable-living/",
  "family": "ideas",
  "title": "更可持续生活的创意和技巧",
  "h1": "更可持续生活的创意和技巧",
  "hero": "/images/pages/cn-zh-ideas-tips-for-more-sustainable-living/img-1.jpg",
  "sections": [
   {
    "heading": "选择更优质的食品",
    "text": "食物的选择会产生不同的影响，从植物性食物到来自负责任来源的认证产品。发现更多简单的方法，轻松实现更可持续的饮食。",
    "image": null
   },
   {
    "heading": "减少浪费",
    "text": "即使生活很节俭，也总会有一定数量的生活垃圾。但有一些简单的方法可以重复利用现有物品并减少家里的浪费。",
    "image": null
   },
   {
    "heading": "延长物品使用寿命",
    "text": "重新利用、修复、再利用、转售或回收产品的潜力不断增长。了解有助于延长家具使用寿命的小方法。",
    "image": null
   },
   {
    "heading": "减少能源消耗",
    "text": "住宅的许多部分都会对能源使用产生直接影响。幸好我们有一些小窍门可以帮助你节省家庭能源。",
    "image": null
   },
   {
    "heading": "节约用水",
    "text": "通过重新审视家庭生活习惯，你每天可以节约很多水。了解一下宜家提供的家庭节水智能解决方案。",
    "image": null
   },
   {
    "heading": "日常生活中的环保理念",
    "text": "我们所有人都可以实现更加可持续的生活方式。",
    "image": null
   },
   {
    "heading": "绿色可持续生活专区",
    "text": "浏览我们的产品系列，开启更可持续的日常生活之旅。",
    "image": null
   },
   {
    "heading": "加入宜家俱乐部",
    "text": "加入会员，享受专属折扣。更多个性化家居灵感，让你的想法照进现实 查看更多",
    "image": null
   },
   {
    "heading": "加入宜家企业会员",
    "text": "加入企业会员，享受会员6大权益以及专属折扣。助力中小微企业共同成长。 查看更多",
    "image": null
   },
   {
    "heading": "常用链接",
    "text": "",
    "image": null
   },
   {
    "heading": "客户服务",
    "text": "",
    "image": null
   },
   {
    "heading": "关于宜家",
    "text": "",
    "image": null
   }
  ],
  "links": [
   "/",
   "/cn/zh/ideas/tips-for-more-sustainable-living/easy-wins-to-eating-more-sustainably-pubdbfa9a20",
   "/cn/zh/ideas/tips-for-more-sustainable-living/simple-ways-to-reduce-waste-at-home-pubb645fb53",
   "/cn/zh/ideas/tips-for-more-sustainable-living/small-steps-to-give-your-furniture-a-longer-life-pubbcff48fc",
   "/cn/zh/ideas/tips-for-more-sustainable-living/quick-tricks-to-save-energy-at-home-pubad783f90",
   "/cn/zh/ideas/tips-for-more-sustainable-living/smart-solutions-to-save-water-at-home-pubfdfe8c45",
   "/cn/zh/this-is-ikea/sustainable-everyday",
   "/cn/zh/cat/700575",
   "/cn/zh/ikea-family",
   "/cn/zh/landing-page/5c84c33b5c95414bacf5f529c9d6a960",
   "/cn/zh/stores/",
   "/cn/zh/planners/",
   "/cn/zh/ikea-family/",
   "/cn/zh/ikea-business/"
  ]
 },
 {
  "url": "/cn/zh/campaigns/wo3-men2-de-chao1-zhi2-di1-jia4-pub8b08af40",
  "family": "campaigns",
  "title": "我们的低价好物-10元好物-20元好物-宜家",
  "h1": "我们的低价好物-10元好物-20元好物-宜家",
  "hero": null,
  "sections": [
   {
    "heading": "低价好物，优选品质",
    "text": "购买价格实惠的家居用品并不意味着牺牲款式、功能和质量。合理的价格让每个人都能负担得起各类日常用品。无论你是计划重新整理衣柜、为孩子的生日派对做准备，还是购买一套新的厨具，宜家一系列价格实惠的配件都能满足你的需求。",
    "image": null
   },
   {
    "heading": "OFTAST 奥夫塔",
    "text": "",
    "image": null
   },
   {
    "heading": "MÅNÖGA 莫诺加",
    "text": "",
    "image": null
   },
   {
    "heading": "VIDEVECKMAL 韦德维冒",
    "text": "",
    "image": null
   },
   {
    "heading": "SLIBB 斯利波",
    "text": "",
    "image": null
   },
   {
    "heading": "UPPFYLLD 乌普菲尔德",
    "text": "",
    "image": null
   },
   {
    "heading": "TREBENT 特莱本",
    "text": "",
    "image": null
   },
   {
    "heading": "UPPFYLLD 乌普菲尔德",
    "text": "柠檬榨汁器, 15 厘米",
    "image": null
   },
   {
    "heading": "FÄRGKLAR 法利克洛",
    "text": "",
    "image": null
   },
   {
    "heading": "SKÅDIS 斯考迪斯",
    "text": "",
    "image": null
   },
   {
    "heading": "NOJIG 诺伊格",
    "text": "收纳盒, 10x10x5 厘米",
    "image": null
   },
   {
    "heading": "HILDEGUN 希德根",
    "text": "厨房用巾, 45x60 厘米",
    "image": null
   }
  ],
  "links": [
   "/",
   "/cn/zh/landing-page/23f07ce063c141f682fdb2e7bc541c7f",
   "/cn/zh/ikea-family",
   "/cn/zh/landing-page/5c84c33b5c95414bacf5f529c9d6a960",
   "/cn/zh/stores/",
   "/cn/zh/planners/",
   "/cn/zh/ikea-family/",
   "/cn/zh/ikea-business/",
   "/landing-page/23f07ce063c141f682fdb2e7bc541c7f/",
   "/cn/zh/as-is-online/",
   "/cn/zh/customer-service/services/buy-back/",
   "/cn/zh/safety-at-home/",
   "/cn/zh/customer-service",
   "/cn/zh/customer-service/contact-us/"
  ]
 },
 {
  "url": "/cn/zh/campaigns/new-lower-price-pubff11f9fb",
  "family": "campaigns",
  "title": "更低价格",
  "h1": "更低价格，给生活更多",
  "hero": "/images/pages/cn-zh-campaigns-new-lower-price-pubff11f9fb/img-1.jpg",
  "sections": [
   {
    "heading": "更低价格",
    "text": "宜家更低价格不是短期的降价促销,而是对低价长期的承诺。 KLUBBSPORRE 克鲁布斯珀勒 人体工学枕，侧卧/仰卧, 41x70 厘米",
    "image": "/images/pages/cn-zh-campaigns-new-lower-price-pubff11f9fb/img-2.jpg"
   },
   {
    "heading": "METOD 米多 / STENSUND 史丹桑德 整体厨房",
    "text": "宜家更低价格不是短期的降价促销,而是对低价长期的承诺。 KLUBBSPORRE 克鲁布斯珀勒 人体工学枕，侧卧/仰卧, 41x70 厘米",
    "image": "/images/pages/cn-zh-campaigns-new-lower-price-pubff11f9fb/img-2.jpg"
   },
   {
    "heading": "￥10,499",
    "text": "宜家更低价格不是短期的降价促销,而是对低价长期的承诺。 KLUBBSPORRE 克鲁布斯珀勒 人体工学枕，侧卧/仰卧, 41x70 厘米",
    "image": "/images/pages/cn-zh-campaigns-new-lower-price-pubff11f9fb/img-2.jpg"
   },
   {
    "heading": "低价目录",
    "text": "按品类查看我们的更低价格产品",
    "image": null
   },
   {
    "heading": "自提商品合集",
    "text": "仅支持自提，线上选购商场取货",
    "image": null
   },
   {
    "heading": "加入宜家俱乐部",
    "text": "加入会员，享受专属折扣。更多个性化家居灵感，让你的想法照进现实 查看更多",
    "image": null
   },
   {
    "heading": "加入宜家企业会员",
    "text": "加入企业会员，享受会员6大权益以及专属折扣。助力中小微企业共同成长。 查看更多",
    "image": null
   },
   {
    "heading": "常用链接",
    "text": "",
    "image": null
   },
   {
    "heading": "客户服务",
    "text": "",
    "image": null
   },
   {
    "heading": "关于宜家",
    "text": "",
    "image": null
   },
   {
    "heading": "宜家新闻",
    "text": "",
    "image": null
   }
  ],
  "links": [
   "/",
   "/cn/zh/p/70570836?artType=art",
   "/cn/zh/p/49514753?artType=SPR",
   "/cn/zh/p/10591667?artType=art",
   "/cn/zh/p/80457236?artType=ART",
   "/cn/zh/inspiration/detail/f4cf93e0-74aa-49b2-bc7e-a1cda18fb8b7?type=IMAGE",
   "/cn/zh/p/pruta-pu-ta-fu-gai-shi-pin-he-17-jian-tao-lu-se-70597100",
   "/cn/zh/p/80583942?artType=art",
   "/cn/zh/p/80574018?artType=art",
   "/cn/zh/inspiration/detail/cbae7293-be2f-40a9-9edd-aa8344d24965?type=IMAGE",
   "/cn/zh/p/klubbsporre-ke-lu-bu-si-po-le-ren-ti-gong-xue-zhen-ce-wo-yang-wo-80446097",
   "/cn/zh/p/30589890?artType=art",
   "/cn/zh/h5page/?url=https://store-companion.ikea.cn/kitchen?channel=EC_APP&cl_sr=kitchen_APP",
   "/cn/zh/landing-page/7b350459dd8e465f9d447bbd6bb704ae"
  ]
 },
 {
  "url": "/cn/zh/campaigns/hopeful-summer-pub72b864f3",
  "family": "campaigns",
  "title": "Hopeful summer",
  "h1": "Hopeful summer",
  "hero": "/images/pages/cn-zh-campaigns-hopeful-summer-pub72b864f3/img-1.jpg",
  "sections": [
   {
    "heading": "桌面好伙伴",
    "text": "",
    "image": null
   },
   {
    "heading": "创意灵感学习角",
    "text": "",
    "image": null
   },
   {
    "heading": "高效有序收纳区",
    "text": "",
    "image": null
   },
   {
    "heading": "让阅读成为顺手的习惯",
    "text": "",
    "image": null
   },
   {
    "heading": "舒适整齐新日常",
    "text": "",
    "image": null
   },
   {
    "heading": "小改变，大不同",
    "text": "",
    "image": null
   },
   {
    "heading": "加入宜家俱乐部",
    "text": "加入会员，享受专属折扣。更多个性化家居灵感，让你的想法照进现实 查看更多",
    "image": null
   },
   {
    "heading": "加入宜家企业会员",
    "text": "加入企业会员，享受会员6大权益以及专属折扣。助力中小微企业共同成长。 查看更多",
    "image": null
   },
   {
    "heading": "常用链接",
    "text": "",
    "image": null
   },
   {
    "heading": "客户服务",
    "text": "",
    "image": null
   },
   {
    "heading": "关于宜家",
    "text": "",
    "image": null
   },
   {
    "heading": "宜家新闻",
    "text": "",
    "image": null
   }
  ],
  "links": [
   "/",
   "/cn/zh/cat/10759",
   "/cn/zh/p/10620448?artType=ART",
   "/cn/zh/p/oekenmarsvin-ou-ken-ma-wen-nao-zhong-huang-se-10620448",
   "/cn/zh/p/70628696?artType=ART",
   "/cn/zh/p/korvsnoere-ke-wa-nuo-lun-led-tai-deng-ke-diao-guang-de-cheng-se-70628696",
   "/cn/zh/p/70531939?artType=ART",
   "/cn/zh/p/krubbet-ke-lu-bei-shou-ji-zhi-jia-hei-se-70531939",
   "/cn/zh/p/skadis-si-kao-di-si-pei-jian-7-jian-tao-hei-se-40586419",
   "/cn/zh/p/korvsnoere-ke-wa-nuo-lun-led-tai-deng-ke-diao-guang-de-bai-se-50624294",
   "/cn/zh/cat/53249",
   "/cn/zh/inspiration/detail/8284CD1E-F711-4606-B22CD2F1752E3B2B",
   "/cn/zh/p/helmer-hai-er-mo-chou-ti-gui-dai-jiao-lun-hong-se-00625026",
   "/cn/zh/p/enkroken-en-ku-ken-shu-zhuo-bai-se-50597083"
  ]
 },
 {
  "url": "/cn/zh/new/meet-the-ikea-ps-2026-collection-pubf28e636c",
  "family": "new",
  "title": "IKEA PS 2026：趣味设计与实用功能碰撞出灵感火花",
  "h1": "了解IKEA PS 2026 系列产品",
  "hero": "/images/pages/cn-zh-new-meet-the-ikea-ps-2026-collection-pubf28e636c/img-1.jpg",
  "sections": [
   {
    "heading": "系列热销中, 正在全力补货",
    "text": "IKEA PS 2026系列自上市以来深受顾客欢迎，目前部分商品库存紧张，我们正在积极组织补货，后续将陆续到货。 该系列为长期销售产品，并非限时发售，请顾客放心选购。您可通过宜家官网/宜家家居App/宜家微信小程序商城 了解最新到货情况。",
    "image": null
   },
   {
    "heading": "简约而不简单的精彩设计",
    "text": "",
    "image": null
   },
   {
    "heading": "空间狭小？那就充分发挥产品的功能性。",
    "text": "",
    "image": null
   },
   {
    "heading": "加入宜家俱乐部",
    "text": "加入会员，享受专属折扣。更多个性化家居灵感，让你的想法照进现实 查看更多",
    "image": null
   },
   {
    "heading": "加入宜家企业会员",
    "text": "加入企业会员，享受会员6大权益以及专属折扣。助力中小微企业共同成长。 查看更多",
    "image": null
   },
   {
    "heading": "常用链接",
    "text": "",
    "image": null
   },
   {
    "heading": "客户服务",
    "text": "",
    "image": null
   },
   {
    "heading": "关于宜家",
    "text": "",
    "image": null
   },
   {
    "heading": "宜家新闻",
    "text": "",
    "image": null
   }
  ],
  "links": [
   "/",
   "/cn/zh/search/products?q=IKEA PS 2026",
   "/cn/zh/p/ikea-ps-2026-luo-di-deng-shen-hong-se-80608513",
   "/cn/zh/p/ikea-ps-2026-dan-ren-sha-fa-chuang-si-ke-te-bo-liang-cheng-se-40620376",
   "/cn/zh/p/ikea-ps-2026-led-bian-xi-shi-deng-ju-dian-chi-cao-zuo-ke-diao-guang-de-lan-se-qian-huang-80613576",
   "/cn/zh/p/ikea-ps-2026-xiu-xian-yi-hua-mu-80621072",
   "/cn/zh/p/ikea-ps-2026-gui-zi-song-mu-60616948",
   "/cn/zh/p/ikea-ps-2026-xiu-xian-yi-pei-you-chong-qi-zuo-yi-yi-bei-kao-dian-ke-nai-bei-ke-liang-lu-se-70623203",
   "/cn/zh/p/50618561?artType=ART",
   "/cn/zh/p/ikea-ps-2026-hua-ping-bo-li-lu-se-bai-se-50618561",
   "/cn/zh/p/00622787?artType=ART",
   "/cn/zh/p/ikea-ps-2026-tai-zhong-hong-se-00622787",
   "/cn/zh/p/40620376?artType=ART",
   "/cn/zh/landing-page/c241884828fd46f5996d74e9761671ff"
  ]
 },
 {
  "url": "/cn/zh/new/let-your-home-come-out-and-play-pubc28e2323",
  "family": "new",
  "title": "给家居添些乐趣，为全家带来趣味玩耍时光",
  "h1": "让家的每个角落都藏着玩趣",
  "hero": "/images/pages/cn-zh-new-let-your-home-come-out-and-play-pubc28e2323/img-1.jpg",
  "sections": [
   {
    "heading": "GREJSIMOJS 格雷希莫",
    "text": "儿童桌, 84x42 厘米",
    "image": null
   },
   {
    "heading": "GREJSIMOJS 格雷希莫",
    "text": "毛绒玩具, 38 厘米",
    "image": null
   },
   {
    "heading": "GREJSIMOJS 格雷希莫",
    "text": "",
    "image": null
   },
   {
    "heading": "GREJSIMOJS 格雷希莫",
    "text": "",
    "image": null
   },
   {
    "heading": "GREJSIMOJS 格雷希莫",
    "text": "长绒地毯, 153x215 厘米",
    "image": null
   },
   {
    "heading": "GREJSIMOJS 格雷希莫",
    "text": "",
    "image": null
   },
   {
    "heading": "GREJSIMOJS 格雷希莫",
    "text": "",
    "image": null
   },
   {
    "heading": "GREJSIMOJS 格雷希莫",
    "text": "被套和枕套, 150x200/50x80 厘米",
    "image": null
   },
   {
    "heading": "GREJSIMOJS 格雷希莫",
    "text": "",
    "image": null
   },
   {
    "heading": "GREJSIMOJS 格雷希莫",
    "text": "",
    "image": null
   },
   {
    "heading": "为玩耍而生",
    "text": "GREJSIMOJS 格雷希莫 系列由12位设计师共同打造，以“探索、创造、想象、运动与竞技”五种玩耍类型为创作框架，使产品既能被轻松使用、拥抱与探索，又能陪伴人们在生活中激发创意灵感。",
    "image": null
   },
   {
    "heading": "奇妙设计，释放生活乐趣",
    "text": "谁说实用和好玩不能兼得？GREJSIMOJS 格雷希莫系列把 “脑洞” 变成日常，让家里的每一件小物，都不止是好看的摆设。",
    "image": null
   }
  ],
  "links": [
   "/",
   "/cn/zh/landing-page/d3cca757933449bd8d8a24586dec15e6",
   "/cn/zh/landing-page/a2abe598cfe4461b9c2dd118a7c6167c",
   "/cn/zh/landing-page/adb76b294fa745318887c836c2f71b8d",
   "/cn/zh/landing-page/de59eb94939e4fb587cbd57fa981f76f",
   "/cn/zh/landing-page/64e2f2efa4eb44cd937c82cbc4cf12f9",
   "/cn/zh/landing-page/24ef04b62d6a488295d37e37d8ee18c2",
   "/cn/zh/p/lyckan-lu-kan-yi-zi-hua-mu-tie-mian-90569224",
   "/cn/zh/p/tranhult-chuan-hu-te-sandshult-sang-de-hu-te-qiang-ge-ban-zu-he-bai-se-bai-yang-mu-89336339",
   "/cn/zh/p/grejsimojs-ge-lei-xi-mo-yi-mao-jia-40611503",
   "/cn/zh/p/grejsimojs-ge-lei-xi-mo-chang-rong-di-tan-lu-se-80602002",
   "/cn/zh/p/kuggis-ku-ji-si-fu-gai-chu-wu-he-bai-se-80526876",
   "/cn/zh/p/dyvlinge-du-wei-lin-ge-xiu-xian-zhuan-yi-qi-lin-cheng-se-80581919",
   "/cn/zh/p/krubbet-ke-lu-bei-shou-ji-zhi-jia-hei-se-70531939"
  ]
 },
 {
  "url": "/cn/zh/ikea-business/",
  "family": "business",
  "title": "宜家对公业务为你省时省钱",
  "h1": "全新设计体验",
  "hero": "/images/pages/cn-zh-ikea-business/img-1.png",
  "sections": [
   {
    "heading": "业务介绍",
    "text": "宜家对公业务IKEA for Business 种类繁多的产品，为企业提供一站式采购服务。 专业设计，服务一对一，为企业提供个性化的设计方案。",
    "image": null
   },
   {
    "heading": "批量采购",
    "text": "种类繁多的产品，为企业提供一站式采购服务。",
    "image": null
   },
   {
    "heading": "商业空间设计",
    "text": "专业设计，服务一对一，为企业提供个性化的设计方案。",
    "image": null
   },
   {
    "heading": "工程项目及合作",
    "text": "提供专业、整体的空间解决方案，全球供应链和强大仓储能力，保证各类项目的落地交付。",
    "image": null
   },
   {
    "heading": "礼品采购",
    "text": "提供高品质产品、多样化选择服务，拓展多元化的合作模式。",
    "image": null
   },
   {
    "heading": "加入宜家企业会员",
    "text": "我们会根据你的业务需求提供相关知识、折扣和各种福利，助力你的业务发展。六大会员权益，从“新”出发，竭诚让您享更好的权益和更省心的服务！​ 新会员礼：新人专享0元购指定商品​ 满额返券：满额返现金券，最高得2500元。​",
    "image": null
   },
   {
    "heading": "商业空间家具和家居设计灵感",
    "text": "无论什么类型的空间，我们都可以效劳。",
    "image": null
   },
   {
    "heading": "用有序桌面唤回灵感",
    "text": "",
    "image": null
   },
   {
    "heading": "真实案例参考",
    "text": "真实还原每张图纸，所见即所得。无论你是店铺开业，公司翻新，学校教育机构等等，宜家都可以帮您一站式解决设计采购等要求。",
    "image": null
   },
   {
    "heading": "专业服务省时省心，轻松高效完成采购",
    "text": "宜家对公业务IKEA for Business 种类繁多的产品，为企业提供一站式采购服务。 专业设计，服务一对一，为企业提供个性化的设计方案。",
    "image": null
   },
   {
    "heading": "在线设计工具",
    "text": "可视化空间，快速获取商品报价",
    "image": null
   },
   {
    "heading": "联系我们，获取专业设计",
    "text": "",
    "image": null
   }
  ],
  "links": [
   "/",
   "/cn/zh/landing-page/cn--zh--db8b3381455d43a2997e7567aa3668d5?productIds=&topProductFullIds=&assemblyProductFullIds=&utm_source=&utm_medium=&utm_campaign=&utm_content=&utm_term=&web_new=",
   "/cn/zh/landing-page/cn--zh--826b2633ecd24b81b26bc0f6c74a47cb?productIds=&topProductFullIds=&assemblyProductFullIds=&utm_source=&utm_medium=&utm_campaign=&utm_content=&utm_term=&web_new=",
   "/cn/zh/landing-page/cn--zh--922524e85f3244acafa07630e5c1f185?productIds=&topProductFullIds=&assemblyProductFullIds=&utm_source=&utm_medium=&utm_campaign=&utm_content=&utm_term=&web_new=",
   "/cn/zh/landing-page/cn--zh--bd104a34eee34072b072631bff64e8d0?productIds=&topProductFullIds=&assemblyProductFullIds=&utm_source=&utm_medium=&utm_campaign=&utm_content=&utm_term=&web_new=",
   "/cn/zh/landing-page/5c84c33b5c95414bacf5f529c9d6a960?productIds=&topProductFullIds=&assemblyProductFullIds=&utm_source=&utm_medium=&utm_campaign=&utm_content=&utm_term=&web_new=",
   "/cn/zh/ikea-business/office-furnishings/",
   "/cn/zh/ikea-business/hospitality-furnishings/yi-jia-dui-gong-ye-wu-min-su-jiu-dian-pub88e3927e",
   "/cn/zh/ikea-business/restaurant-cafe-furnishings/can-yin-ji-gou-pub45ff42de",
   "/cn/zh/ikea-business/jiao4-yu4-pei2-xun4-kong1-jian1-puba9f5c960",
   "/cn/zh/ikea-business/retail-furnishings/",
   "/cn/zh/cat/10573",
   "/cn/zh/p/skadis-si-kao-di-si-dong-dong-ban-mu-tou-80347177",
   "/cn/zh/p/skadis-si-kao-di-si-pei-jian-7-jian-tao-bai-se-80586417"
  ]
 },
 {
  "url": "/cn/zh/ikea-business/pi-liang-cai-gou-pub826b2633",
  "family": "business",
  "title": "商业空间设计",
  "h1": "商业空间设计",
  "hero": null,
  "sections": [
   {
    "heading": "我们为您提供",
    "text": "IKEA for Business 专业设计，服务一对一，为企业提供个性化的设计方案。 企业会员10元/每平米，非会员15元/每平米。免费注册。",
    "image": null
   },
   {
    "heading": "专业设计师一对一服务",
    "text": "",
    "image": null
   },
   {
    "heading": "即时在线回复，北欧风格设计",
    "text": "",
    "image": null
   },
   {
    "heading": "产品符合中国和欧洲环保标准放心使用",
    "text": "",
    "image": null
   },
   {
    "heading": "企业会员专享设计优惠",
    "text": "企业会员10元/每平米，非会员15元/每平米。免费注册。",
    "image": null
   },
   {
    "heading": "真实案例参考",
    "text": "真实还原每张图纸，所见即所得。无论你是店铺开业，公司翻新，学校教育机构等等，宜家都可以帮您一站式解决设计采购等要求。",
    "image": null
   },
   {
    "heading": "更多解决方案，塑造空间更多的可能性",
    "text": "IKEA for Business 专业设计，服务一对一，为企业提供个性化的设计方案。 企业会员10元/每平米，非会员15元/每平米。免费注册。",
    "image": null
   },
   {
    "heading": "MITTZON 米特丛系列 - 健康办公解决方案，让办公变得生动健康。",
    "text": "IKEA for Business 专业设计，服务一对一，为企业提供个性化的设计方案。 企业会员10元/每平米，非会员15元/每平米。免费注册。",
    "image": null
   },
   {
    "heading": "我们的服务流程",
    "text": "",
    "image": null
   },
   {
    "heading": "联系宜家对公业务部",
    "text": "· 预约设计服务： < 立即预约 > · 联系 < 本地商场的对公业务部 > · 企业采购热线：400 800 2345",
    "image": null
   },
   {
    "heading": "加入宜家俱乐部",
    "text": "加入会员，享受专属折扣。更多个性化家居灵感，让你的想法照进现实 查看更多",
    "image": null
   },
   {
    "heading": "加入宜家企业会员",
    "text": "加入企业会员，享受会员6大权益以及专属折扣。助力中小微企业共同成长。 查看更多",
    "image": null
   }
  ],
  "links": [
   "/",
   "/cn/zh/h5page/?url=https://store-companion.ikea.cn/design-leads/ib.html?channel=IRW+M2&cl_sr=IB_IRW+M2a.cn/design-leads/ib.html?channel=IRW+M2&cl_sr=IB_IRW+M2",
   "/cn/zh/h5page/?url=https://store-companion.ikea.cn/design-leads/ib.html?channel=IRW+M2&cl_sr=IB_IRW+M2a.cn%2Fdesign-leads%2Fib.html",
   "/cn/zh/people-and-planet/",
   "/cn/zh/landing-page/5c84c33b5c95414bacf5f529c9d6a960",
   "/cn/zh/ikea-business/office-furnishings/",
   "/cn/zh/ikea-business/hospitality-furnishings/yi-jia-dui-gong-ye-wu-min-su-jiu-dian-pub88e3927e",
   "/cn/zh/ikea-business/restaurant-cafe-furnishings/can-yin-ji-gou-pub45ff42de",
   "/cn/zh/ikea-business/jiao4-yu4-pei2-xun4-kong1-jian1-puba9f5c960",
   "/cn/zh/ikea-business/retail-furnishings/",
   "/cn/zh/ikea-business/ben-di-shi-ji-an-li-pubab418f94",
   "/cn/zh/pages/cn--zh--ab418f94a52e4b7995b164c117433981",
   "/cn/zh/h5page/?url=https://store-companion.ikea.cn/ib?channel=IRW%20M2&cl_sr=IB_IRW%20M2",
   "/cn/zh/customer-service/services/assembly/"
  ]
 },
 {
  "url": "/cn/zh/ikea-business/comprehensive-solutions/gong-cheng-xiang-mu-ji-he-zuo-pub922524e8",
  "family": "business",
  "title": "工程项目及合作",
  "h1": "工程项目及合作",
  "hero": "/images/pages/cn-zh-ikea-business-comprehensive-solutions-gong-cheng-xiang-mu-ji-he-zuo-pub922524e8/img-1.jpg",
  "sections": [
   {
    "heading": "人才/长租公寓解决方案",
    "text": "",
    "image": null
   },
   {
    "heading": "中大型企业办公",
    "text": "",
    "image": null
   },
   {
    "heading": "加入宜家俱乐部",
    "text": "加入会员，享受专属折扣。更多个性化家居灵感，让你的想法照进现实 查看更多",
    "image": null
   },
   {
    "heading": "加入宜家企业会员",
    "text": "加入企业会员，享受会员6大权益以及专属折扣。助力中小微企业共同成长。 查看更多",
    "image": null
   },
   {
    "heading": "常用链接",
    "text": "",
    "image": null
   },
   {
    "heading": "客户服务",
    "text": "",
    "image": null
   },
   {
    "heading": "关于宜家",
    "text": "",
    "image": null
   },
   {
    "heading": "宜家新闻",
    "text": "",
    "image": null
   }
  ],
  "links": [
   "/",
   "/cn/zh/h5page/?url=https://store-companion.ikea.cn/design-leads/ib.html?channel=IRW+M2&cl_sr=IB_IRW+M2 宜家设计预约  ",
   "/cn/zh/customer-service/services/assembly/",
   "/cn/zh/ikea-family",
   "/cn/zh/landing-page/5c84c33b5c95414bacf5f529c9d6a960",
   "/cn/zh/stores/",
   "/cn/zh/planners/",
   "/cn/zh/ikea-family/",
   "/cn/zh/ikea-business/",
   "/landing-page/23f07ce063c141f682fdb2e7bc541c7f/",
   "/cn/zh/as-is-online/",
   "/cn/zh/customer-service/services/buy-back/",
   "/cn/zh/safety-at-home/",
   "/cn/zh/customer-service"
  ]
 },
 {
  "url": "/cn/zh/ikea-business/gift-purchasing/li-pin-cai-gou-pubbd104a34",
  "family": "business",
  "title": "礼品采购",
  "h1": "礼品采购服务",
  "hero": "/images/pages/cn-zh-ikea-business-gift-purchasing-li-pin-cai-gou-pubbd104a34/img-1.png",
  "sections": [
   {
    "heading": "满足您多样化的礼品采购需求！",
    "text": "",
    "image": null
   },
   {
    "heading": "员工福利",
    "text": "品类繁多的产品满足多种多样的需求。",
    "image": null
   },
   {
    "heading": "市场营销",
    "text": "品牌相互加持，合作共赢！",
    "image": null
   },
   {
    "heading": "积分兑换",
    "text": "",
    "image": null
   },
   {
    "heading": "商务礼赠",
    "text": "",
    "image": null
   },
   {
    "heading": "选择您的采购类型：",
    "text": "IKEA for Business - 国际化品控体系- 近万种产品型号- 全网统一零售价- 批量生产价更优 品类繁多的产品满足多种多样的需求。",
    "image": "/images/pages/cn-zh-ikea-business-gift-purchasing-li-pin-cai-gou-pubbd104a34/img-2.png"
   },
   {
    "heading": "宜家实物礼品",
    "text": "",
    "image": null
   },
   {
    "heading": "定制礼盒",
    "text": "",
    "image": null
   },
   {
    "heading": "加入宜家俱乐部",
    "text": "加入会员，享受专属折扣。更多个性化家居灵感，让你的想法照进现实 查看更多",
    "image": null
   },
   {
    "heading": "加入宜家企业会员",
    "text": "加入企业会员，享受会员6大权益以及专属折扣。助力中小微企业共同成长。 查看更多",
    "image": null
   },
   {
    "heading": "常用链接",
    "text": "",
    "image": null
   },
   {
    "heading": "客户服务",
    "text": "",
    "image": null
   }
  ],
  "links": [
   "/",
   "/cn/zh/ikea-business/gift-box/li-he-shi-wu-li-pin-puba532ca16",
   "/cn/zh/apps/ikea-business/gift",
   "/cn/zh/h5page/?url=https://store-companion.ikea.cn/design-leads/ib.html?channel=IRW+M2&cl_sr=IB_IRW+M2 宜家设计预约  ",
   "/cn/zh/customer-service/services/assembly/",
   "/cn/zh/ikea-family",
   "/cn/zh/landing-page/5c84c33b5c95414bacf5f529c9d6a960",
   "/cn/zh/stores/",
   "/cn/zh/planners/",
   "/cn/zh/ikea-family/",
   "/cn/zh/ikea-business/",
   "/landing-page/23f07ce063c141f682fdb2e7bc541c7f/",
   "/cn/zh/as-is-online/",
   "/cn/zh/customer-service/services/buy-back/"
  ]
 },
 {
  "url": "/cn/zh/landing-page/cn--zh--9bdb3af1c07611e8affa0d09be91682d",
  "family": "landing",
  "title": "宜家家居官网-宜家电商-提供客厅，卧室，厨房，各类家居灵感和产品解决方案",
  "h1": "我们的服务",
  "hero": null,
  "sections": [
   {
    "heading": "加入宜家俱乐部",
    "text": "加入会员，享受专属折扣。更多个性化家居灵感，让你的想法照进现实 查看更多",
    "image": null
   },
   {
    "heading": "加入宜家企业会员",
    "text": "加入企业会员，享受会员6大权益以及专属折扣。助力中小微企业共同成长。 查看更多",
    "image": null
   },
   {
    "heading": "常用链接",
    "text": "",
    "image": null
   },
   {
    "heading": "客户服务",
    "text": "",
    "image": null
   },
   {
    "heading": "关于宜家",
    "text": "",
    "image": null
   },
   {
    "heading": "宜家新闻",
    "text": "",
    "image": null
   }
  ],
  "links": [
   "/",
   "/cn/zh/h5page/?url=https://store-companion.ikea.cn/design-leads/wrd.html?channel=EC_website&cl_sr=IRW_homepage_3nd&design_version=GPC_case&source=NEW_WEB",
   "/cn/zh/h5page/?url=https://store-companion.ikea.cn/kitchen?channel=kitchen_IRW%20M2&cl_sr=IRW%20M2",
   "/cn/zh/ikea-business/",
   "/cn/zh/customer-service/services/delivery/",
   "/cn/zh/customer-service/services/assembly/",
   "/cn/zh/customer-service/services/kitchen-planning/",
   "/cn/zh/customer-service/services/kitchen-installation/",
   "/cn/zh/customer-service/services/removal-recycling/",
   "/cn/zh/customer-service/returns-claims/return-policy/",
   "/cn/zh/customer-service/services/lipinka-pubf2366e21",
   "/cn/zh/customer-service/services/wan2-zheng3-chuang1-lian2-fu2-wu4-pubab28e5d0",
   "/cn/zh/customer-service/services/click-collect/",
   "/cn/zh/customer-service/payment-options/"
  ]
 },
 {
  "url": "/cn/zh/landing-page/5c84c33b5c95414bacf5f529c9d6a960",
  "family": "landing",
  "title": "宜家家居官网-宜家电商-提供客厅，卧室，厨房，各类家居灵感和产品解决方案",
  "h1": "宜家家居官网-宜家电商-提供客厅，卧室，厨房，各类家居灵感和产品解决方案",
  "hero": "/images/pages/cn-zh-landing-page-5c84c33b5c95414bacf5f529c9d6a960/img-1.jpg",
  "sections": [
   {
    "heading": "宜家企业会员",
    "text": "加入宜家企业会员，我们会根据你的业务需求提供相关知识、有力折扣和各种福利，助力你的业务发展。 新会员礼：新人专享0元购指定商品​ 满额返券：满额返现金券，最高得2500元。​",
    "image": "/images/pages/cn-zh-landing-page-5c84c33b5c95414bacf5f529c9d6a960/img-2.jpg"
   },
   {
    "heading": "加入企业会员 →",
    "text": "加入宜家企业会员，我们会根据你的业务需求提供相关知识、有力折扣和各种福利，助力你的业务发展。 新会员礼：新人专享0元购指定商品​ 满额返券：满额返现金券，最高得2500元。​",
    "image": "/images/pages/cn-zh-landing-page-5c84c33b5c95414bacf5f529c9d6a960/img-2.jpg"
   },
   {
    "heading": "加入只需简单3步",
    "text": "加入宜家企业会员，我们会根据你的业务需求提供相关知识、有力折扣和各种福利，助力你的业务发展。 新会员礼：新人专享0元购指定商品​ 满额返券：满额返现金券，最高得2500元。​",
    "image": "/images/pages/cn-zh-landing-page-5c84c33b5c95414bacf5f529c9d6a960/img-2.jpg"
   },
   {
    "heading": "宜企老带新，双赢欢乐购",
    "text": "2026.4.3-2026.8.30 获得推荐资格的老会员，推荐业务伙伴注册成为企业新会员，并完成买单即有好礼相赠，多买多赠。​",
    "image": null
   },
   {
    "heading": "满额返券",
    "text": "宜家企业会员专享满额返现金券，多买多返，最高得2500元。​ *活动详情咨询宜家对公业务",
    "image": null
   },
   {
    "heading": "新会员礼​",
    "text": "企业会员新人专享0元购指定宜家商品，注册成功后当日获得一张礼品券，凭券可到店进行换购指定商品一件，具体见礼品券细则。​",
    "image": null
   },
   {
    "heading": "无门槛免费设计",
    "text": "每年定期赠送宜家企业会员无门槛免费设计服务一次，可以获得从大件家具到细节装饰，整体商业空间解决方案。​ *设计服务不含线下测量服务​",
    "image": null
   },
   {
    "heading": "免费停车",
    "text": "宜家企业会员可享受工作日免费停车3小时，周末节假日，商场活动日除外。如何领取免费停车券：宜家企业会员至商场宜家对公业务，出示宜家企业会员卡领取3小时免费停车券。",
    "image": null
   }
  ],
  "links": [
   "/",
   "/cn/zh/h5page/?url=http://datayi.cn/6qGXnabidMbjx",
   "/cn/zh/landing-page/cn--zh--f25254565cf340cca030afdc3f1aeb3e",
   "/cn/zh/landing-page/4182948b527941679a947145f49f8db5",
   "/cn/zh/landing-page/acf1961d1be245b8adf85e35d2cd9c5e",
   "/cn/zh/landing-page/b4ec81a633764d8ea9d1001b0a261ba9",
   "/cn/zh/landing-page/0635f77a0ab9403fb2805930575e4671",
   "/cn/zh/ikea-family",
   "/cn/zh/landing-page/5c84c33b5c95414bacf5f529c9d6a960",
   "/cn/zh/stores/",
   "/cn/zh/planners/",
   "/cn/zh/ikea-family/",
   "/cn/zh/ikea-business/",
   "/landing-page/23f07ce063c141f682fdb2e7bc541c7f/"
  ]
 },
 {
  "url": "/cn/zh/customer-service/services/delivery/",
  "family": "services",
  "title": "送货服务_宜家",
  "h1": "送货服务",
  "hero": null,
  "sections": [
   {
    "heading": "我们的服务",
    "text": "",
    "image": null
   },
   {
    "heading": "加入宜家俱乐部",
    "text": "加入会员，享受专属折扣。更多个性化家居灵感，让你的想法照进现实 查看更多",
    "image": null
   },
   {
    "heading": "加入宜家企业会员",
    "text": "加入企业会员，享受会员6大权益以及专属折扣。助力中小微企业共同成长。 查看更多",
    "image": null
   },
   {
    "heading": "常用链接",
    "text": "",
    "image": null
   },
   {
    "heading": "客户服务",
    "text": "",
    "image": null
   },
   {
    "heading": "关于宜家",
    "text": "",
    "image": null
   },
   {
    "heading": "宜家新闻",
    "text": "",
    "image": null
   }
  ],
  "links": [
   "/",
   "/cn/zh/customer-service/services/assembly/",
   "/cn/zh/customer-service/services/kitchen-planning/",
   "/cn/zh/customer-service/services/kitchen-installation/",
   "/cn/zh/customer-service/services/removal-recycling/",
   "/cn/zh/customer-service/services/",
   "/cn/zh/ikea-family",
   "/cn/zh/landing-page/5c84c33b5c95414bacf5f529c9d6a960",
   "/cn/zh/stores/",
   "/cn/zh/planners/",
   "/cn/zh/ikea-family/",
   "/cn/zh/ikea-business/",
   "/landing-page/23f07ce063c141f682fdb2e7bc541c7f/",
   "/cn/zh/as-is-online/"
  ]
 },
 {
  "url": "/cn/zh/customer-service/services/assembly/",
  "family": "services",
  "title": "组装服务_宜家",
  "h1": "组装服务",
  "hero": null,
  "sections": [
   {
    "heading": "服务项目及收费标准",
    "text": "",
    "image": null
   },
   {
    "heading": "- 宜家组装服务",
    "text": "该服务是由宜家的服务供应商提供的，您也可以向宜家工作人员咨询。 注：少部分地区可能应用与下面不同的组装费用（线下购买时请和店内宜家员工确认）。",
    "image": null
   },
   {
    "heading": "- “万师傅”平台组装服务",
    "text": "该服务由宜家合作的共享服务平台“万师傅”提供。仅针对家具类商品提供组装服务。 收费标准：平台为竞价模式，发布任务后，顾客依据师傅的信息，自愿选择一名师傅上门完成服务。 下单方式：微信小程序搜索“万师傅家庭版”，或扫描二维码自助下单。",
    "image": null
   },
   {
    "heading": "我们的服务",
    "text": "",
    "image": null
   },
   {
    "heading": "加入宜家俱乐部",
    "text": "加入会员，享受专属折扣。更多个性化家居灵感，让你的想法照进现实 查看更多",
    "image": null
   },
   {
    "heading": "加入宜家企业会员",
    "text": "加入企业会员，享受会员6大权益以及专属折扣。助力中小微企业共同成长。 查看更多",
    "image": null
   },
   {
    "heading": "常用链接",
    "text": "",
    "image": null
   },
   {
    "heading": "客户服务",
    "text": "",
    "image": null
   },
   {
    "heading": "关于宜家",
    "text": "",
    "image": null
   },
   {
    "heading": "宜家新闻",
    "text": "",
    "image": null
   }
  ],
  "links": [
   "/",
   "/cn/zh/customer-service/contact-us/",
   "/cn/zh/customer-service/services/delivery/",
   "/cn/zh/customer-service/services/kitchen-planning/",
   "/cn/zh/customer-service/services/kitchen-installation/",
   "/cn/zh/customer-service/services/removal-recycling/",
   "/cn/zh/customer-service/services/",
   "/cn/zh/ikea-family",
   "/cn/zh/landing-page/5c84c33b5c95414bacf5f529c9d6a960",
   "/cn/zh/stores/",
   "/cn/zh/planners/",
   "/cn/zh/ikea-family/",
   "/cn/zh/ikea-business/",
   "/landing-page/23f07ce063c141f682fdb2e7bc541c7f/"
  ]
 },
 {
  "url": "/cn/zh/customer-service/services/kitchen-planning/",
  "family": "services",
  "title": "设计服务_宜家",
  "h1": "设计服务",
  "hero": "/images/pages/cn-zh-customer-service-services-kitchen-planning/img-1.jpg",
  "sections": [
   {
    "heading": "衣柜设计服务",
    "text": "",
    "image": null
   },
   {
    "heading": "客厅储物设计服务",
    "text": "",
    "image": null
   },
   {
    "heading": "我们的服务",
    "text": "",
    "image": null
   },
   {
    "heading": "加入宜家俱乐部",
    "text": "加入会员，享受专属折扣。更多个性化家居灵感，让你的想法照进现实 查看更多",
    "image": null
   },
   {
    "heading": "加入宜家企业会员",
    "text": "加入企业会员，享受会员6大权益以及专属折扣。助力中小微企业共同成长。 查看更多",
    "image": null
   },
   {
    "heading": "常用链接",
    "text": "",
    "image": null
   },
   {
    "heading": "客户服务",
    "text": "",
    "image": null
   },
   {
    "heading": "关于宜家",
    "text": "",
    "image": null
   },
   {
    "heading": "宜家新闻",
    "text": "",
    "image": null
   }
  ],
  "links": [
   "/",
   "/cn/zh/h5page/?url=https://store-companion.ikea.cn/design-leads/wrd.html?channel=EC_website&cl_sr=customer_service",
   "/cn/zh/h5page/?url=https://store-companion.ikea.cn/kitchen?channel=kitchen_IRW%20M2&cl_sr=IRW%20M2&_ga=2.29755199.1246865819.1603076366-578008148.1596011551",
   "/cn/zh/ikea-business/",
   "/cn/zh/h5page/?url=https://kefu.csc.ikea.cn/webim/im.html?configId=4ddd4cac-0db9-42c0-907b-2ef3c9b6dd9a",
   "/cn/zh/customer-service/contact-us/",
   "/cn/zh/customer-service/services/delivery/",
   "/cn/zh/customer-service/services/assembly/",
   "/cn/zh/customer-service/services/kitchen-installation/",
   "/cn/zh/customer-service/services/removal-recycling/",
   "/cn/zh/customer-service/services/",
   "/cn/zh/ikea-family",
   "/cn/zh/landing-page/5c84c33b5c95414bacf5f529c9d6a960",
   "/cn/zh/stores/"
  ]
 },
 {
  "url": "/cn/zh/customer-service/services/kitchen-installation/",
  "family": "services",
  "title": "宜家安装服务-安装家具拆装家具",
  "h1": "安装服务",
  "hero": null,
  "sections": [
   {
    "heading": "服务项目及收费标准",
    "text": "宜家安装服务由专业安装团队确保服务品质，精准落实设计。产品和服务分开收费， 价格透明。根据你的厨房或浴室设计方案，向工作人员了解安装服务详情，购买需要的服务。 省时省心省力，轻松实现理想厨房浴室！ 如果您因为个人原因改变原定安装日期，请在原定安装时间前一日提出，并应在原定安装时间往后三十一日之内再次选择并完成您的安装服务，具体日期以宜家客服和您联系后商定的日期为准。 宜家厨房安装服务由专业安装团队确保服务品质，精准落实设计。产品和服务分开收费，价格透明。根据你的厨房设计方案，向工作人员了解安装服务详情，购买需要的服务。省时省心省力，轻松实现理想厨房！",
    "image": null
   },
   {
    "heading": "注意事项",
    "text": "宜家安装服务由专业安装团队确保服务品质，精准落实设计。产品和服务分开收费， 价格透明。根据你的厨房或浴室设计方案，向工作人员了解安装服务详情，购买需要的服务。 省时省心省力，轻松实现理想厨房浴室！ 如果您因为个人原因改变原定安装日期，请在原定安装时间前一日提出，并应在原定安装时间往后三十一日之内再次选择并完成您的安装服务，具体日期以宜家客服和您联系后商定的日期为准。 宜家厨房安装服务由专业安装团队确保服务品质，精准落实设计。产品和服务分开收费，价格透明。根据你的厨房设计方案，向工作人员了解安装服务详情，购买需要的服务。省时省心省力，轻松实现理想厨房！",
    "image": null
   },
   {
    "heading": "厨房安装服务",
    "text": "宜家厨房安装服务由专业安装团队确保服务品质，精准落实设计。产品和服务分开收费，价格透明。根据你的厨房设计方案，向工作人员了解安装服务详情，购买需要的服务。省时省心省力，轻松实现理想厨房！",
    "image": null
   },
   {
    "heading": "完整厨房安装：",
    "text": "以上厨房安装服务与价格仅适用于在当地有宜家商场的城市。完整厨房安装：包括橱柜、门板、层压板台面、盖板、踢脚板、操作台面支撑板（垫板）、墙面防溅挡板（层压板）、厨房飞檐等装饰条、把手、水龙头、水槽、厨房照明、置物架、挂杆和内部配件等。安装过程中所有柜体和盖板涉及到的局部切割、开孔和不超过3个柜体的整体切割改宽度和深度。接触空气的切割露出面需用铝箔纸包边。注：为确保安装顺利进行，请提前自行安装好水管三角阀，并准备需要加长的上下水管。",
    "image": null
   },
   {
    "heading": "其他厨房安装服务 :",
    "text": "宜家安装服务由专业安装团队确保服务品质，精准落实设计。产品和服务分开收费， 价格透明。根据你的厨房或浴室设计方案，向工作人员了解安装服务详情，购买需要的服务。 省时省心省力，轻松实现理想厨房浴室！ 如果您因为个人原因改变原定安装日期，请在原定安装时间前一日提出，并应在原定安装时间往后三十一日之内再次选择并完成您的安装服务，具体日期以宜家客服和您联系后商定的日期为准。 宜家厨房安装服务由专业安装团队确保服务品质，精准落实设计。产品和服务分开收费，价格透明。根据你的厨房设计方案，向工作人员了解安装服务详情，购买需要的服务。省时省心省力，轻松实现理想厨房！",
    "image": null
   },
   {
    "heading": "非完整厨房安装：",
    "text": "宜家安装服务由专业安装团队确保服务品质，精准落实设计。产品和服务分开收费， 价格透明。根据你的厨房或浴室设计方案，向工作人员了解安装服务详情，购买需要的服务。 省时省心省力，轻松实现理想厨房浴室！ 如果您因为个人原因改变原定安装日期，请在原定安装时间前一日提出，并应在原定安装时间往后三十一日之内再次选择并完成您的安装服务，具体日期以宜家客服和您联系后商定的日期为准。 宜家厨房安装服务由专业安装团队确保服务品质，精准落实设计。产品和服务分开收费，价格透明。根据你的厨房设计方案，向工作人员了解安装服务详情，购买需要的服务。省时省心省力，轻松实现理想厨房！",
    "image": null
   },
   {
    "heading": "宜家进口厨房电器安装费：",
    "text": "以上厨房安装服务与价格仅适用于在当地有宜家商场的城市。如你在宜家购买了完整厨房（含宜家进口厨房电器），我们提供宜家厨房电器安装服务。注：需要确认家中安装施工条件，并根据日常需要准备安装辅料，如角阀、三通等，更多详情请咨询店内工作人员。",
    "image": null
   },
   {
    "heading": "宜家旧厨房拆除服务",
    "text": "宜家安装服务由专业安装团队确保服务品质，精准落实设计。产品和服务分开收费， 价格透明。根据你的厨房或浴室设计方案，向工作人员了解安装服务详情，购买需要的服务。 省时省心省力，轻松实现理想厨房浴室！ 如果您因为个人原因改变原定安装日期，请在原定安装时间前一日提出，并应在原定安装时间往后三十一日之内再次选择并完成您的安装服务，具体日期以宜家客服和您联系后商定的日期为准。 宜家厨房安装服务由专业安装团队确保服务品质，精准落实设计。产品和服务分开收费，价格透明。根据你的厨房设计方案，向工作人员了解安装服务详情，购买需要的服务。省时省心省力，轻松实现理想厨房！",
    "image": null
   },
   {
    "heading": "厨房拆除费：¥499/套",
    "text": "宜家安装服务由专业安装团队确保服务品质，精准落实设计。产品和服务分开收费， 价格透明。根据你的厨房或浴室设计方案，向工作人员了解安装服务详情，购买需要的服务。 省时省心省力，轻松实现理想厨房浴室！ 如果您因为个人原因改变原定安装日期，请在原定安装时间前一日提出，并应在原定安装时间往后三十一日之内再次选择并完成您的安装服务，具体日期以宜家客服和您联系后商定的日期为准。 宜家厨房安装服务由专业安装团队确保服务品质，精准落实设计。产品和服务分开收费，价格透明。根据你的厨房设计方案，向工作人员了解安装服务详情，购买需要的服务。省时省心省力，轻松实现理想厨房！",
    "image": null
   },
   {
    "heading": "浴室安装服务",
    "text": "宜家浴室安装服务由专业安装团队确保服务品质，精准落实设计。产品和服务分开收费，价格透明。根据你的厨房设计方案，向工作人员了解安装服务详情，购买需要的服务。省时省心省力，轻松实现理想浴室！",
    "image": null
   },
   {
    "heading": "宜家旧浴室拆除服务",
    "text": "宜家安装服务由专业安装团队确保服务品质，精准落实设计。产品和服务分开收费， 价格透明。根据你的厨房或浴室设计方案，向工作人员了解安装服务详情，购买需要的服务。 省时省心省力，轻松实现理想厨房浴室！ 如果您因为个人原因改变原定安装日期，请在原定安装时间前一日提出，并应在原定安装时间往后三十一日之内再次选择并完成您的安装服务，具体日期以宜家客服和您联系后商定的日期为准。 宜家厨房安装服务由专业安装团队确保服务品质，精准落实设计。产品和服务分开收费，价格透明。根据你的厨房设计方案，向工作人员了解安装服务详情，购买需要的服务。省时省心省力，轻松实现理想厨房！",
    "image": null
   },
   {
    "heading": "浴室拆除费：¥299/套",
    "text": "宜家安装服务由专业安装团队确保服务品质，精准落实设计。产品和服务分开收费， 价格透明。根据你的厨房或浴室设计方案，向工作人员了解安装服务详情，购买需要的服务。 省时省心省力，轻松实现理想厨房浴室！ 如果您因为个人原因改变原定安装日期，请在原定安装时间前一日提出，并应在原定安装时间往后三十一日之内再次选择并完成您的安装服务，具体日期以宜家客服和您联系后商定的日期为准。 宜家厨房安装服务由专业安装团队确保服务品质，精准落实设计。产品和服务分开收费，价格透明。根据你的厨房设计方案，向工作人员了解安装服务详情，购买需要的服务。省时省心省力，轻松实现理想厨房！",
    "image": null
   }
  ],
  "links": [
   "/",
   "/cn/zh/customer-service/services/delivery/",
   "/cn/zh/customer-service/services/assembly/",
   "/cn/zh/customer-service/services/kitchen-planning/",
   "/cn/zh/customer-service/services/removal-recycling/",
   "/cn/zh/customer-service/services/",
   "/cn/zh/ikea-family",
   "/cn/zh/landing-page/5c84c33b5c95414bacf5f529c9d6a960",
   "/cn/zh/stores/",
   "/cn/zh/planners/",
   "/cn/zh/ikea-family/",
   "/cn/zh/ikea-business/",
   "/landing-page/23f07ce063c141f682fdb2e7bc541c7f/",
   "/cn/zh/as-is-online/"
  ]
 },
 {
  "url": "/cn/zh/planners/",
  "family": "planners",
  "title": "设计工具",
  "h1": "设计与规划",
  "hero": "/images/pages/cn-zh-planners/img-1.jpg",
  "sections": [
   {
    "heading": "精心设计你的房间",
    "text": "使用房间设计工具，你可以创建详细的空间方案；设计你的厨房和浴室空间。",
    "image": null
   },
   {
    "heading": "打造适合你的空间和需求的产品设计",
    "text": "产品设计工具是一种简单易用的宜家设计工具，可以帮助你创建一个复杂的产品解决方案，满足你的需求。 在这些设计工具中，你可以添加和删除模块化部件和内部配件，并保存你的设计以备之后使用。",
    "image": null
   },
   {
    "heading": "自定义理想的储物方案",
    "text": "为家中所有区域规划和设计不同的储物方案。使用PAX 帕克思 衣柜设计工具设计自己的衣柜，或者使用BESTÅ 贝达 设计工具打造独特的客厅储物方案。",
    "image": null
   },
   {
    "heading": "组合你的理想沙发",
    "text": "借助模块化沙发设计工具，你可以用不同的模块或沙发套打造心仪的沙发组合。选择一款契合个性风格的沙发，然后为你的家居空间量身定制解决方案。",
    "image": null
   },
   {
    "heading": "玩转书桌",
    "text": "借助书桌设计工具，你可以组合不同的桌面，桌腿和储物柜，从而简单轻松地打造适合你的书桌。",
    "image": null
   },
   {
    "heading": "为你构思和设计理想厨房",
    "text": "厨房设计工具是一款快速简单的工具，可让将你的ENHET 安纳特 厨房组合自定义为最适合你家庭的解决方案。",
    "image": null
   },
   {
    "heading": "使用舒适睡眠指南优化你的睡眠",
    "text": "通过我们的舒睡眠指南，找到你理想的床垫。只需回答几个简单的问题，我们将分析你的回答，为你提供量身定制的建议，帮助你获得最佳睡眠。",
    "image": null
   },
   {
    "heading": "需要帮助吗？",
    "text": "设计中遇到困难或者想要咨询问题，我们有线上专业设计师免费为你服务。",
    "image": null
   },
   {
    "heading": "加入宜家俱乐部",
    "text": "加入会员，享受专属折扣。更多个性化家居灵感，让你的想法照进现实 查看更多",
    "image": null
   },
   {
    "heading": "加入宜家企业会员",
    "text": "加入企业会员，享受会员6大权益以及专属折扣。助力中小微企业共同成长。 查看更多",
    "image": null
   },
   {
    "heading": "常用链接",
    "text": "",
    "image": null
   },
   {
    "heading": "客户服务",
    "text": "",
    "image": null
   }
  ],
  "links": [
   "/",
   "/cn/zh/h5page/?url=https://kitchen.planner.ikea.cn/planner/#/cn/zh/",
   "/cn/zh/planners/bathroom-planner/?layout=headless",
   "/cn/zh/h5page/?url=https://www.ikea.cn/addon-app/space/platform/latest/cn/zh/#/room/living-room",
   "/cn/zh/h5page/?url=https://www.ikea.cn/addon-app/space/platform/latest/cn/zh/#/room/childrens-room",
   "/cn/zh/h5page/?url=https://www.ikea.cn/addon-app/space/platform/latest/cn/zh/#/room/bedroom",
   "/cn/zh/h5page/?url=https://www.ikea.cn/addon-app/space/platform/latest/cn/zh/#/room/workspace",
   "/cn/zh/h5page/?url=https://www.ikea.cn/addon-app/space/platform/latest/cn/zh/#/room/dining",
   "/cn/zh/h5page/?url=https://www.ikea.cn/addon-app/space/platform/latest/cn/zh/#/room/hallway",
   "/cn/zh/h5page/?url=https://www.ikea.cn/addon-app/space/platform/latest/cn/zh/#/room/outdoor",
   "/cn/zh/planners/pax-planner/?layout=headless",
   "/cn/zh/planners/kallax-planner/?layout=headless",
   "/cn/zh/planners/besta-planner/?layout=headless",
   "/cn/zh/planners/platsa-planner/?layout=headless"
  ]
 },
 {
  "url": "/cn/zh/rooms/bedroom/LASTARE-serie-pub03fdc74e",
  "family": "rooms-articles",
  "title": "LASTARE 拉思塔尔 储物系列",
  "h1": "越生活 越有序​",
  "hero": null,
  "sections": [
   {
    "heading": "LASTARE 拉思塔尔 系列",
    "text": "生活不必完美，但需要有序。LASTARE 拉思塔尔系列以灵活组合与简单设计，让收纳自然融入日常，在不断增加的物品与越来越丰富的生活中始终保持从容与舒适。​",
    "image": null
   },
   {
    "heading": "LASTARE 拉思塔尔",
    "text": "四斗抽屉柜, 60x42x103 厘米",
    "image": null
   },
   {
    "heading": "LASTARE 拉思塔尔",
    "text": "衣柜组合, 180x42x201 厘米",
    "image": null
   },
   {
    "heading": "LASTARE 拉思塔尔",
    "text": "衣柜组合, 60x42x103 厘米",
    "image": null
   },
   {
    "heading": "LASTARE 拉思塔尔",
    "text": "搁架组合, 80x42x103 厘米",
    "image": null
   },
   {
    "heading": "LASTARE 拉思塔尔",
    "text": "衣柜组合, 60x42x201 厘米",
    "image": null
   },
   {
    "heading": "LASTARE 拉思塔尔",
    "text": "框架, 80x42x100 厘米",
    "image": null
   },
   {
    "heading": "LASTARE 拉思塔尔",
    "text": "四斗抽屉柜, 60x42x100 厘米",
    "image": null
   },
   {
    "heading": "LASTARE 拉思塔尔",
    "text": "储物组合, 210x42x103 厘米",
    "image": null
   },
   {
    "heading": "LASTARE 拉思塔尔",
    "text": "四斗抽屉柜, 40x42x100 厘米",
    "image": null
   },
   {
    "heading": "LASTARE 拉思塔尔",
    "text": "衣柜组合, 160x42x201 厘米",
    "image": null
   },
   {
    "heading": "自主设计，自由搭配",
    "text": "试一试我们的自主设计工具，亲手打造属于自己的 LASTARE 拉思塔尔 储物组合吧！",
    "image": null
   }
  ],
  "links": [
   "/",
   "/cn/zh/search/products?q=LASTARE",
   "/cn/zh/planners/lastare-planner/?layout=headless",
   "/cn/zh/search/products?q=lastare衣柜",
   "/cn/zh/p/lastare-la-si-ta-er-yi-gui-zu-he-bai-se-dai-jia-gao-jian-79619329",
   "/cn/zh/p/lindbyn-lin-de-bi-en-jing-zi-hei-se-50590449",
   "/cn/zh/p/nymane-niu-mo-nai-bi-deng-yue-du-deng-bai-se-60356988",
   "/cn/zh/p/stuk-si-tu-ke-7-ge-chu-wu-jian-bai-se-hui-se-00370869",
   "/cn/zh/p/lastare-la-si-ta-er-yi-gui-zu-he-bai-se-09619337",
   "/cn/zh/p/agam-a-gan-er-tong-yi-hei-se-70253536"
  ]
 },
 {
  "url": "/cn/zh/rooms/living-room/-ae-li-le-sai-te--puba9cf4fd8",
  "family": "rooms-articles",
  "title": "LILLESÄTER 利乐塞特",
  "h1": "LILLESÄTER 利乐塞特",
  "hero": null,
  "sections": [
   {
    "heading": "全新沙发系列",
    "text": "",
    "image": null
   },
   {
    "heading": "Love it. Live it 布置自在舒适的客厅",
    "text": "",
    "image": null
   },
   {
    "heading": "LILLESÄTER 利乐塞特",
    "text": "",
    "image": null
   },
   {
    "heading": "LILLESÄTER 利乐塞特",
    "text": "",
    "image": null
   },
   {
    "heading": "LILLESÄTER 利乐塞特",
    "text": "",
    "image": null
   },
   {
    "heading": "LILLESÄTER 利乐塞特",
    "text": "",
    "image": null
   },
   {
    "heading": "LILLESÄTER 利乐塞特",
    "text": "",
    "image": null
   },
   {
    "heading": "LILLESÄTER 利乐塞特",
    "text": "",
    "image": null
   },
   {
    "heading": "LILLESÄTER 利乐塞特",
    "text": "",
    "image": null
   },
   {
    "heading": "LILLESÄTER 利乐塞特",
    "text": "",
    "image": null
   },
   {
    "heading": "LILLESÄTER 利乐塞特",
    "text": "",
    "image": null
   },
   {
    "heading": "LILLESÄTER 利乐塞特",
    "text": "",
    "image": null
   }
  ],
  "links": [
   "/",
   "/cn/zh/p/lillesaeter-li-le-sai-te-xiu-xian-zhuan-yi-gang-na-rui-de-shen-lan-se-90618489",
   "/cn/zh/p/lillesaeter-li-le-sai-te-ai-deng-gang-na-rui-de-shen-lan-se-00618484",
   "/cn/zh/p/lillesaeter-li-le-sai-te-san-ren-sha-fa-a-si-wo-hui-bai-20619072",
   "/cn/zh/p/varmblixt-wang-bu-li-led-tai-deng-bi-deng-cheng-se-bo-li-yuan-xing-40525143",
   "/cn/zh/p/klippoxel-ke-li-bo-sai-xiu-xian-tan-hui-bai-50584622",
   "/cn/zh/p/lillesaeter-li-le-sai-te-san-ren-sha-fa-gang-na-rui-de-qian-lu-se-huang-se-60618495",
   "/cn/zh/p/lillesaeter-li-le-sai-te-xiu-xian-zhuan-yi-a-si-wo-hui-bai-80618687",
   "/cn/zh/p/lillesaeter-li-le-sai-te-ai-deng-a-si-wo-hui-bai-00619068",
   "/cn/zh/p/froetorp-fu-rui-tuo-pu-cha-ji-bai-se-du-ge-bai-se-bo-li-90622090"
  ]
 }
];
